### ISSUE TITLE
line 566: -: syntax error: operand expected (error token is "-")

### ISSUE THREAD

**Issue by tjmcewan** [myspaghetti/macos-guest-virtualbox#100]
I'm using bash 5 on a mac os host, installed via brew.  I think there's also something wrong with the version detection.  I tried to run the script on bash 5.0.11 from brew and bash-4.4.18 directly from the gnu website.  They both output the lines below.  Even after I removed the entire `declare` block (lines 566-699) for debugging, the version check still failed in bash 5.

```
bash-5.0$ ./macos-guest-virtualbox.sh
./macos-guest-virtualbox.sh: line 566: -: syntax error: operand expected (error token is "-")
Please run this script on BASH 4.0 or higher.
```

**Comment by myspaghetti** [comment]
The script runs on `/bin/bash` which is bash 3 on macOS. If you wish to run it with a different bash, you need to execute it as `/path/to/new/bash macos-guest-virtualbox.sh`
