### ISSUE TITLE
Consider adjusting minimum `storagesize` to support Catalina

### ISSUE THREAD

**Issue by pricebenjamin** [myspaghetti/macos-guest-virtualbox#102]
When attempting to install Catalina (10.15 beta), the macOS terminal outputs the following error:

```
Error: The selected volume is not large enough to install on. A minimum of 23.27 GB is required.
```

This error occurs immediately after executing the `start_the_installer_app` stage.

Setting `storagesize=24000` solves this issue. Perhaps the minimum should be adjusted?

https://github.com/myspaghetti/macos-guest-virtualbox/blob/5827dc76a86436dfa9c38825b979a57885967dc3/macos-guest-virtualbox.sh#L14

**Comment by myspaghetti** [comment]
Implemented in [version 0.75.4](https://github.com/myspaghetti/macos-guest-virtualbox/commit/3ac0ef190a4106545f0b34da5fede8577a0c59b2#diff-cdaa9e2d5d0bf4d2f0d5e5e82c446516)
