### ISSUE TITLE
help me, im lost

### ISSUE THREAD

**Issue by JMS1717** [myspaghetti/macos-guest-virtualbox#105]
i don't know whats going on, I have no idea how do to this. does this even work on windows?

**Comment by myspaghetti** [comment]
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
2. Install [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads)
3. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`, `wget`, and `unzip`
4. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
5. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash ./macos-guest-virtualbox.sh`)
