### ISSUE TITLE
The VM doesn't show up in Virtual Box Manager app

### ISSUE THREAD

**Issue by federicorossini09** [myspaghetti/macos-guest-virtualbox#106]
Hi, I successfully ran the script in Ubuntu 18.04 using Virtualbox v6.0.12. After configuring the OS, i manually shutdown the VM. Some minutes later I wanted to boot the VM again from the Virtualbox Manager but It wasn't there. What could have happen? How can I boot the VM again? Thanks.

**Comment by myspaghetti** [comment]
Does the target VDI (by default `macOS.vdi`) still exist? If so then you just need to make sure the `.vbox` file exists (by default `macOS.vbox` in a subdirectory in your default VirtualBox VM path). If it doesn't exist, you can recreate it manually or with `./macos-guest-virtualbox create_vm configure-vm` and then attach `macOS.vdi` to the virtual machine with `VBoxManage` or through the GUI.

If you don't find the VDI or the `.vbox` file please locate the `VBox.log` file and attach it here.

**Comment by federicorossini09** [comment]
Hi, thanks for the answer. I manage to find the .vbox file. It was in a folder wich I had no permissions to access. I could access It and I now I'm finally running the VM again. Thanks for the great work, I'm totally recomending this.
