### ISSUE TITLE
Qemu/KVM Import

### ISSUE THREAD

**Issue by KaisserbenDll** [myspaghetti/macos-guest-virtualbox#107]
Can you maybe provide some guidelines for the virtual image import to KVM/QEMU ? 

I made an .ova image extract it .vmdk image and converted it to .qcow2 with qemu-img. 
However when i created the image with Virtual-machine program, it is stuck in booting from hard Disk. This would be of great help. I really need the USB port recognition in the virutalbox, That is why i am doing all this.

**Comment by myspaghetti** [comment]
Sorry, KVM requires advanced configuration. See [macOS-Simple-KVM](https://github.com/foxlet/macOS-Simple-KVM). The difference between the scripts is that this one doesn't use Clover or preconfigured disk images, while macOS-Simple-KVM does.

**Comment by KaisserbenDll** [comment]
The script is a very solid work. Thank you for the response. macOS simple KVM didn't work, however i could fix what i needed with your script.  
Good job writing that script

**Comment by user747** [comment]
> Sorry, KVM requires advanced configuration. See [macOS-Simple-KVM](https://github.com/foxlet/macOS-Simple-KVM). The difference between the scripts is that this one doesn't use Clover or preconfigured disk images, while macOS-Simple-KVM does.

any known alternatives or guides that don't rely on Clover to get QEMU support working? Converting from vdi to qcow2 or raw is relatively straight forward. 

its great that this script is vanilla from start to finish. will continue search for vanilla route from vbox to QEMU.

**Comment by cgilles** [comment]
I vote also for QEmu support, even if emulated arm64 on Intel processor can be slow. But this can help in some use-cases.
Else, as UTM do, QEmu can also visualize Arm64 on Arm64 and in this case the performance are very good.
