### ISSUE TITLE
Start vm on Xeon multicore server fails due to CPU ID

### ISSUE THREAD

**Issue by jonsito** [myspaghetti/macos-guest-virtualbox#109]
I have problems to start Catalina vm on first boot, showing several UEFI boot problems.

To solve it I added following line to change CPU ID:
----------------------------------------------------- cut here -------------------
--- macos-guest-virtualbox.sh	2019-10-17 13:31:45.980533851 +0200
+++ macos-guest-virtualbox.sh.orig	2019-10-17 13:27:07.747334562 +0200
@@ -514,9 +514,6 @@
  --boot4 none --firmware efi --rtcuseutc on --usbxhci on --chipset ich9 \
  --mouse usbtablet --keyboard usb --audiocontroller hda --audiocodec stac9221
 
-#JAMC
-VBoxManage modifyvm "${vmname}" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
-
 VBoxManage setextradata "${vmname}" \
  "VBoxInternal/Devices/efi/0/Config/DmiSystemFamily" "${DmiSystemFamily}"
 VBoxManage setextradata "${vmname}" \
----------------------------------------------------- cut here -------------------

Expect that this helps you. Thanks for the script
Juan Antonio

**Comment by myspaghetti** [comment]
Thanks for the info. For other CPUs that require custom settings see [issue 8](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8).
