### ISSUE TITLE
startup.nsh aborts after fs3:

### ISSUE THREAD

**Issue by smk762** [myspaghetti/macos-guest-virtualbox#111]
Attempted Mojave and High Sierra, with following result after final install step.
Using Virtualbox 6.0.14 r133895 on Ubuntu 18.04
![image](https://user-images.githubusercontent.com/35845239/67138832-c31f0500-f27b-11e9-8b2e-c574d225c00f.png)

**Comment by myspaghetti** [comment]
Can reproduce. `startup.nsh` aborts for some reason.

**Comment by myspaghetti** [comment]
Temporary fix: on the EFI shell, enter `fs0:` and then `edit startup.nsh` and [remove the first "endfor" and the two lines directly below it](https://github.com/myspaghetti/macos-guest-virtualbox/commit/7bde335163a43c1c5930b5bb763a7006e6fc5292). I'll see why it aborts and fix it in the next version.

**Comment by smk762** [comment]
thanks, will try and report back

**Comment by myspaghetti** [comment]
The latest version of VirtualBox (6.0.14) aborts `startup.nsh` when a command fails. Added `if` statements to avoid this behavior.

Fixed in [version 0.76.0](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/0642d90ac73af4d2f7ebbc4083529fdfc58da0ae/macos-guest-virtualbox.sh)
