### ISSUE TITLE
Any hint for cloning? ( EFI boot problem after "vboxmanage clonemedium" )

### ISSUE THREAD

**Issue by jonsito** [myspaghetti/macos-guest-virtualbox#112]
I can use provided script without problems, but when I try to clone vdi, resulting image won't boot

I've replicated configuration from original vbox file, so both vms are allmost identical (apart of uuid's ). however, on boot process cloned vm fires so many mesages about EFI files not found and hangs, refusing to start os
¿Whats the right way to clone a Catalina vdi image getting it bootable?

My goal is to  NFS readonly export cloned Catalina image to serve as immutable/multiattach vdi base for several mac clients in an student's lab ( as I usually do with otherl linux and Windows images )

Thanks in advance
Juan Antonio

**Comment by myspaghetti** [comment]
Cloning works without any extra steps; what you're seeing is [issue 111](https://github.com/myspaghetti/macos-guest-virtualbox/issues/111), for some reason the `startup.nsh` script aborts with the most recent version of VirtualBox. The linked issue has a description for a temporary fix.
