### ISSUE TITLE
  Error after shutdown

### ISSUE THREAD

**Issue by ranielli** [myspaghetti/macos-guest-virtualbox#115]
![image](https://user-images.githubusercontent.com/1909238/68075388-e2db2080-fd85-11e9-9535-37b3863afb3e.png)

Error after shutdown

**Comment by myspaghetti** [comment]
Can you specify the last few outputs from the script on the host machine? The last 10 lines or so would do.

**Comment by myspaghetti** [comment]
Closing until further information is provided.
