### ISSUE TITLE
Error executing script, wants bash 5

### ISSUE THREAD

**Issue by senyacullen** [myspaghetti/macos-guest-virtualbox#116]
I'm using bash 5 but I still get the following error

./macos-guest-virtualbox.sh: line 576: -: syntax error: operand expected (error token is "-")
Please run this script on BASH 4.0 or higher.

Trying to run on MacOS 10.15.1

**Comment by myspaghetti** [comment]
macOS `/bin/bash` is bash 3. Make sure you run the script with `/path/to/bash5 macos-guest-virtualbox.sh`
