### ISSUE TITLE
Can't progress past selecting OS version (Ubuntu 19.04)

### ISSUE THREAD

**Issue by senyacullen** [myspaghetti/macos-guest-virtualbox#117]
Press a key to select the macOS version to install on the virtual machine:   
 [H]igh Sierra (10.13)
 [M]ojave (10.14)
 [C]atalina (10.15)

 [H/M/C] C
Catalina selected
./macos-guest-virtualbox.sh: line 1006: vmname=MacOS: command not found
./macos-guest-virtualbox.sh: line 1006: storagesize=30000: command not found
./macos-guest-virtualbox.sh: line 1006: cpucount=2: command not found
./macos-guest-virtualbox.sh: line 1006: memorysize=2048: command not found
./macos-guest-virtualbox.sh: line 1006: gpuvram=128: command not found
./macos-guest-virtualbox.sh: line 1006: resolution=1280x800: command not found

**Comment by myspaghetti** [comment]
It appears you have run the script with a command like that looks like so: `./macos-guest-virtualbox.sh vmname=MacOS  storagesize=30000 cpucount=2 memorysize=2048 gpuvram=128 resolution=1280x800`. This is invalid, the script only accepts the command line options specified in `./macos-guest-virtualbox.sh stages` . To set these *variables*, you need to edit the script itself. They appear at the top of the script in a function called `set_variables()`.
