### ISSUE TITLE
ApfsDriverLoader.efi not found, can't mount VISO file

### ISSUE THREAD

**Issue by copypasteearth** [myspaghetti/macos-guest-virtualbox#119]
VISO: RTVfsQueryPathInfo failed on ApfsDriverLoader.efi (relative to C:\Users\copyp\MAC): VERR_FILE_NOT_FOUND (VERR_FILE_NOT_FOUND).
VD: error VERR_FILE_NOT_FOUND opening image file 'C:\Users\copyp\MAC\Catalina_installation_files.viso' (VERR_FILE_NOT_FOUND).
Failed to open image 'C:\Users\copyp\MAC\Catalina_installation_files.viso' in read-only mode (VERR_FILE_NOT_FOUND).
AHCI: Failed to attach drive to Port3 (VERR_FILE_NOT_FOUND).

the file is there but virtual box says it cannot find it.
through the script when it first starts virtual box it opens for a second and then closes so I opened up virtual box and tried to open the vm manually and I get the error above

how do I fix this?

**Comment by myspaghetti** [comment]
Please attach `${HOME}/.VirtualBox/Machines/macOS/Logs/vbox.log`

Make sure VirtualBox in not in headless mode.

**Comment by copypasteearth** [comment]
[VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/3828145/VBox.log)
here is the log file, how do you check if VirtualBox is in headless mode?

**Comment by myspaghetti** [comment]
According to the log, VirtualBox is not in headless mode and the version is correct so that's good.

```
00:00:14.148974 visoOpenWorker: RTFsIsoMakerCmdEx failed: VERR_FILE_NOT_FOUND - RTVfsQueryPathInfo failed on ApfsDriverLoader.efi (relative to C:\Users\copyp\MAC): VERR_FILE_NOT_FOUND
```
It's possible the script failed to download `AppleSupport-v2.0.4-RELEASE.zip` or that `unzip` failed to correctly extract files from it.

Is there a file called `ApfsDriverLoader.efi` in the script's working directory, and are its permissions correct?

**Comment by copypasteearth** [comment]
no ApfsDriverLoader..efi is not in the working directory.  the AppleSupport-v2.0.4-RELEASE.zip is there but there is nothing in it

**Comment by copypasteearth** [comment]
I also get this while running the script in bash

> Downloading open-source APFS EFI drivers
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2019-11-10 01:35:09--  https://github.com/acidanthera/AppleSupportPkg/releases/download/2.0.4/AppleSupport-v2.0.4-RELEASE.zip
Resolving github.com... 140.82.113.4
Connecting to github.com|140.82.113.4|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
Archive:  AppleSupport-v2.0.4-RELEASE.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in AppleSupport-v2.0.4-RELEASE.zip,
        and cannot find AppleSupport-v2.0.4-RELEASE.zip.zip, period.

**Comment by copypasteearth** [comment]
I just went to that link from above and got the zip and extracted it and put the files in the directory and the machine started up

**Comment by myspaghetti** [comment]
Apparently your `wget` version is so old it doesn't support `tlsv1`. Closing as `won'tfix` although it's possible in the future the script will check that files are actually downloaded properly.
