### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by leoheck** [myspaghetti/macos-guest-virtualbox#120]
First of all, your script is awesome. Thank you.

Do you know what should I do to set the fullscreen mode?
Should I install the guest additions?

Do you have any tutorial/script to try this?
> After successfully creating a working macOS virtual machine, consider importing it into QEMU/KVM so it can run with hardware passthrough at near-native performance.

**Comment by leoheck** [comment]
I also was not able to install XCode, the drive is not big enough. Is it possible to increase it without running everything from the beginning?

**Comment by myspaghetti** [comment]
- Fullscreen mode is entered with HOST+F
- VirtualBox does not provide guest additions for macOS guests, but VMware Tools works.
- QEMU/KVM requires some hardware-specific configuration and no support is offered. [There's a guide for QEMU passthrough here.](https://passthroughpo.st/mac-os-vm-guide-part-2-gpu-passthrough-and-tweaks/)

**Comment by leoheck** [comment]
Sure, but `HOST+F` is not working. At least for me. It makes the window full screen, but the macOS desktop remains the same size.

> QEMU/KVM requires some hardware-specific configuration and no support is offered. There's a guide for QEMU passthrough here.

Cool, thanks.

**Comment by o6uoq** [comment]
I'm seeing the same issue as @leoheck - the mac cannot resize to match host screen size/scale.

**Comment by myspaghetti** [comment]
That's because there are no VirtualBox guest additions for macOS at the moment. You can try installing VMware Tools, which offers similar features.

**Comment by o6uoq** [comment]
@myspaghetti thanks for the quick response. Assuming VMware Tools will require a separate install of macOS or I can use/leverage my existing macOS VB install ?

**Comment by myspaghetti** [comment]
You can install it on the existing VM. I haven't tested it in a while, not sure it still works.

**Comment by myspaghetti** [comment]
You can install it on the existing VM. I haven't tested it in a while, not sure it still works. Worst-case scenario, export the VirtualBox VM to VMWare.

**Comment by danieltomasz** [comment]
@leoheck To change screen size after instaling use (put your specific screen resolution)
`VBoxManage setextradata "macOS" "VBoxInternal2/EfiGraphicsResolution" "1920x1080"`

https://superuser.com/questions/478901/change-macos-x-guest-screen-resolution-for-virtualbox

**Comment by o6uoq** [comment]
I tried the *VBoxManage* command however it did not work, I suspect because I was defining a resolution greater than `1920x1200` (which seems to be the max). Now that I've set it to that, it's working! Not sure about full screen tho, installed VB guest additions, no luck.
