### ISSUE TITLE
What do I exactly uncomment/replace to make connected Apple applications work in the script?

### ISSUE THREAD

**Issue by Gangster8192** [myspaghetti/macos-guest-virtualbox#123]
The script says that I need to uncomment the below commented commands to make connected apple applications work. Are these commands: `# system_profiler SPHardwareDataType`, `# ioreg -l | grep -m 1 board-id`, `# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB | awk '{ print $NF }'`, `# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM | awk '{ print $NF }'`, `# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM | awk '{ print $NF }'`, and `# csrutil status`?

Anything else I need to change like the Serial \#, UUID, or anything like that?

**Comment by Gangster8192** [comment]
Sorry if this is not the place to ask these questions, I don't see anywhere else I could ask for help for this exact script.

**Comment by Gangster8192** [comment]
If I run this script without filling in these variables, will I have to run the entire script over again?

**Comment by myspaghetti** [comment]
I changed the phrasing in [version 0.76.2](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/96292ae1743e25f25b7233de5c8a005bf6030908/macos-guest-virtualbox.sh) to reflect that the commented commands need to be run on a genuine Mac. They are not part of the script.

When run on a genuine Mac, they provide the values for the variables that follow them in the script. For example `system_profiler SPHardwareDataType` provides the model name, identifier, system serial, etc, and `ioreg -l | grep -m 1 board-id` provides the value for `DmiBoardProduct`.

macOS installs fine without customizing these values. You can change these values after installation by editing the script and running `./macos-guest-virtualbox set_variables`

**Comment by o6uoq** [comment]
`macOS installs fine without customizing these values. You can change these values after installation by editing the script and running ./macos-guest-virtualbox set_variables`

Are you suggesting that once someone has successfully run and installed `macos-guest-virtualbox.sh` they then run it _again_ with `set_variables` flag?

**Comment by myspaghetti** [comment]
If they want to change the EFI and NVRAM parameters, yes. See the section "iCloud and iMessage connectivity" when accessing the documentation with `./macos-guest-virtualbox.sh documentation`
