### ISSUE TITLE
Steps to use this script

### ISSUE THREAD

**Issue by sarik12** [myspaghetti/macos-guest-virtualbox#124]
Hello, can anyone please provide steps to use this script, i am not able to follow up. Thanks!

**Comment by myspaghetti** [comment]
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
2. Install [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads)
3. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`, `wget`, and `unzip`
4. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
5. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash ./macos-guest-virtualbox.sh`)
