### ISSUE TITLE
How to import the VM to KVM?

### ISSUE THREAD

**Issue by sebastiandg7** [myspaghetti/macos-guest-virtualbox#125]
The VM is working fine in virtualbox. I tried creating a .qcow2 disk from the .vdi. Then create a KVM VM with that disk but it is stuck at boot.

**Comment by myspaghetti** [comment]
You need to configure your VM. See [macOS-Simple-KVM](https://github.com/foxlet/macOS-Simple-KVM/blob/master/tools/template.xml.in) for example.
