### ISSUE TITLE
Issue trying to open the VM at all

### ISSUE THREAD

**Issue by Ufinexa** [myspaghetti/macos-guest-virtualbox#129]
Pretty new to this but got this error when it tried to launch the VM on its own, tried on two versions of VB as well, newest and one before it. 
![NVIDIA_Share_2019-11-21_13-46-29](https://user-images.githubusercontent.com/46165534/69343440-87ee6800-0c65-11ea-98ff-430f522aede0.png)

**Comment by myspaghetti** [comment]
The error message means that one of the configured VM variables should be of type `bytes` but isn't. The script variables `MLB`, `ROM`, `SYSTEM_UUID`, and `SYSTEM_INTEGRITY_PROTECTION` are set to strings that begin with `bytes:` by default. They may have been edited.

If you still can't find the issue please attach `%HOMEDRIVE%%HOMEPATH%\\.VirtualBox\\Machines\\macOS\\Logs\vbox.log`

**Comment by myspaghetti** [comment]
The error message means that one of the configured VM variables should be of type `bytes` but isn't. The script variables `MLB`, `ROM`, `SYSTEM_UUID`, and `SYSTEM_INTEGRITY_PROTECTION` are set to strings that begin with `bytes:` by default. They may have been edited.

If you still can't find the issue please attach `%HOMEDRIVE%%HOMEPATH%\VirtualBox VMs\macOS\Logs\vbox.log`
