### ISSUE TITLE
WSL2

### ISSUE THREAD

**Issue by icanhazpython** [myspaghetti/macos-guest-virtualbox#131]
https://github.com/myspaghetti/macos-guest-virtualbox/blob/97a848a8fdc1327e5557037e96c1de334c9ce28c/macos-guest-virtualbox.sh#L199

The mentioned line attempts to match an uppercase "Microsoft". On my particular install (Win 10 Pro version 2004, build 19033.1, using WSL2), running `cat /proc/sys/kernel/osrelease` yields `4.19.84-microsoft-standard`. This does not properly match the bash condition as the match is case sensitive. Adding `shopt -s nocasematch` in the beginning of the script should alleviate this issue.

**Comment by myspaghetti** [comment]
Does the script work on WSL2? Did they fix the issue with Hyper-V not releasing the virtualization hardware?

**Comment by myspaghetti** [comment]
Added WSL2 detection in [version 0.76.4](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/bf6bf77ad1b0e67a71d2aecf3af73dfcea24c2f8/macos-guest-virtualbox.sh). WSL2 is not supported.

**Comment by myspaghetti** [comment]
It appears running Hyper-V still renders VirtualBox nearly unusable.

**Comment by rahilwazir** [comment]
@myspaghetti I believe both VirtualBox and VMWare Workstation now works with Hyper-V enabled.
Confirmed: https://twitter.com/richturn_ms/status/1271621832685191169

But I still get the same error as OP reported, using WSL2 (regardless of Hypver-V enabled or not).

Am I missing something?

**Comment by myspaghetti** [comment]
@rahilwazir despite what richturn_ms says, their screenshot shows VirtualBox using NEM with no hardware-supported acceleration. It's true VirtualBox works without hardware-supported acceleration but a macOS guest will not work without it.

**Comment by rahilwazir** [comment]
@myspaghetti So seems like WSL2 is not supported, and once the following is sorted out

> Did they fix the issue with Hyper-V not releasing the virtualization hardware?

It will work with WSL2?

**Comment by myspaghetti** [comment]
Yes, but Microsoft does not plan to do so.

**Comment by Velocet** [comment]
You are mixing up two Windows features: _Hyper-V_ and the new _Virtual Machine Platform_ (_Windows Hypervisor Platform_). I don't have any Hyper-V functionality enabled and VMware works fine. I can even run VMware alongside my WSL2 distros. For WSL2 to work you only need the Virtual Machine Platform feature and nothing else (expect the Windows Subsystem for Linux).

You could check which features are enabled in an elevated PowerShell with this command:  
`Get-WindowsOptionalFeature -Online | where State -eq Enabled | ft`

Please let me know if there are any test i could run for you to clear things up.

**Comment by myspaghetti** [comment]
@Velocet please execute the following:
```
echo "vm_name=vtx_test_${RANDOM}" > macos_vm_vars_file
export macos_vm_vars_file=macos_vm_vars_file
./macos-guest-virtualbox.sh create_vm check_default_virtual_machine troubleshoot
```
Then upload the file `vtx_test_*_troubleshoot.txt`

You will see that [WSL2 uses Hyper-V](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq) and that VirtualBox falls back on NEM without hardware-supported virtualization.

**Comment by myspaghetti** [comment]
@Velocet please execute the following:
```
echo "vm_name=vtx_test_${RANDOM}" > macos_vm_vars_file
export macos_vm_vars_file=macos_vm_vars_file
./macos-guest-virtualbox.sh create_vm check_default_virtual_machine
./macos-guest-virtualbox.sh troubleshoot
```
Then upload the file `vtx_test_*_troubleshoot.txt`

You will see that [WSL2 uses Hyper-V](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq) and that VirtualBox falls back on NEM without hardware-supported virtualization.
