### ISSUE TITLE
After restart ... 

### ISSUE THREAD

**Issue by Tigerrrr19** [myspaghetti/macos-guest-virtualbox#132]
Hi, how can i Boot after restarting my laptop,? In Virtualbox I don’t have macOS Sierra. Thanks!

**Comment by myspaghetti** [comment]
You probably ran the script as a user in a group for which VirtualBox doesn't have file reading permissions. Find the `macOS.vbox` file, add it as a virtual machine, attach the `macOS.vdi` file to it, and start it. If the configuration is corrupt, create a VM and run `macos-guest-virtualbox.sh configure_vm`, then attach `macOS.vdi` and start the VM.
