### ISSUE TITLE
Apple Device Enrollment Program (DEP) and guest machines

### ISSUE THREAD

**Issue by vol24pl** [myspaghetti/macos-guest-virtualbox#133]
```
# system_profiler SPHardwareDataType
# ioreg -l | grep -m 1 board-id
# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB | awk '{ print $NF }'
# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM | awk '{ print $NF }'
# ioreg -l -p IODeviceTree | grep \"system-id
# csrutil status
```

Getting this data from a real Mac hardware will let you login to iCloud/AppStore 

Will providing this data from the [DEP](https://www.apple.com/business/docs/site/DEP_Guide.pdf) Macbook, make the guest enrolled as well? If so which data should I omit so it wouldn't happen?

I cannot test this myself as I currently don't have a DEP enrolled hardware.

**Comment by myspaghetti** [comment]
Closing issue for lack of replies; feel free to reply and reopen.

**Comment by myspaghetti** [comment]
@vol24pl see [issue 158](https://github.com/myspaghetti/macos-guest-virtualbox/issues/158) for virtual machine DEP enrollment

**Comment by Oujiii** [comment]
In gonna comment here just so we have the issues separated. What exactly are you trying to achieve?

**Comment by startergo** [comment]
I think if two machines advertise their ID's to the Apple servers as identical values the user account maybe locked. What is funny is that I have a VMWARE machine with fully working Imessage and icloud in this format:
```
 Model Name:	Apple device
  Model Identifier:	VMware7,1
  Boot ROM Version:	VMW71.00V.16068103.B64.2004200145
  Apple ROM Info:	[MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]Welcome to the Virtual Machine
  SMC Version (system):	1.16f8
  Serial Number (system):	VM<numbers>+IN
  Hardware UUID:	00000000-0000-####-####-000#########
