### ISSUE TITLE
Installing Mojave - Last step, installer is not rebooting the VM

### ISSUE THREAD

**Issue by gzr58l** [myspaghetti/macos-guest-virtualbox#137]
Installing Mojave on 
VirtualBox 6.0, 
Host: Ubuntu 19.10 (64 bit)
Processor: Intel Core i5-47505 CPU @ 2.90GHxx4
RAM 12 GiB

Script expecting a reboot after installation is completed but noting is happening.  Terminal prompt on VM is ready.  Please view screens below.

![base_apple](https://user-images.githubusercontent.com/2244269/71182504-d0d11680-223b-11ea-812f-a47b90fa9cf2.png)
![script_screen](https://user-images.githubusercontent.com/2244269/71182516-d595ca80-223b-11ea-9243-0d2f7158991b.png)

**Comment by myspaghetti** [comment]
Hi! Please paste the output of `ls` of the script's working directory on the host. It should look like this:
```
 ApfsDriverLoader.efi                Mojave_installation_files.viso
 AppleImageLoader.efi                Mojave_InstallESD.part00
 AppleSupport-v2.0.4-RELEASE.zip     Mojave_InstallESD.part01
 AppleUiSupport.efi                  Mojave_InstallESD.part02
'Install Mojave.vdi'                 Mojave_InstallESD.part03
 macOS.vdi                           Mojave_InstallESD.part04
 macos-guest-virtualbox.sh           Mojave_InstallESD.part05
 Mojave_AppleDiagnostics.chunklist   Mojave_InstallESD.part06
 Mojave_AppleDiagnostics.dmg         Mojave_InstallESDDmg.pkg
 Mojave_BaseSystem.chunklist         Mojave_InstallInfo.plist
 Mojave_BaseSystem.dmg               startup.nsh
 Mojave_BaseSystem.vdi
```

And please paste the output of the following from the guest Terminal:
```
ls /Volumes/Mojav-files/
ls /Install*.app/Contents/SharedSupport/
```

**Comment by gzr58l** [comment]
Thank you for the quick response.  Here are the screenshots you asked for.
![Screenshot of host](https://user-images.githubusercontent.com/2244269/71209743-ef520480-2271-11ea-9ca9-2be8a547ab0d.png)
![Screenshot from guest](https://user-images.githubusercontent.com/2244269/71209744-f1b45e80-2271-11ea-80cb-9ddb6bb30dc3.png)

**Comment by gzr58l** [comment]
For whatever it is worth...i noticed that the VM version is MacOC 10.13 High Sierra, even through I selected Mohave.

![Screenshot-Sierra](https://user-images.githubusercontent.com/2244269/71210539-b6fef600-2272-11ea-8d26-5a056f99682e.png)
![Screenshot-Mojave](https://user-images.githubusercontent.com/2244269/71210545-b9615000-2272-11ea-9c58-ba5edfa564b1.png)

**Comment by myspaghetti** [comment]
Please run in the guest Terminal:
`for file in /Install*.app/Contents/SharedSupport/; do md5 "${file}"; done`
The output should be:
```
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/AppleDiagnostics.chunklist) = 9ecb9bd94257dbd6eda65049750979c4
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/AppleDiagnostics.dmg) = 46789046cc0a4377c2513cb53fbe00d1
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.chunklist) = ce2c02a6669dd02d830a97afc285ce17
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/BaseSystem.dmg) = b10c7482b32c747283536f29d1c4b9ca
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg) = 3ffc64e9a5fd3d1cb65314432c3b1c53
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/InstallInfo.plist) = 23112d9ef2fea53c1dd1bcd3c91e1f0a
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/InstallInfo.plist.bak) = c6ea60bdc05652f06141c284a86b4618
MD5 (/Install macOS Mojave.app/Contents/SharedSupport/InstallInfo.plist.bak2) = 200370cd98efe44016abe68f94ed1ac2
```

The VirtualBox settings are correct (High Sierra is the latest macOS supported), all the files are there. If the checksums do not match then shut down the guest and delete the file(s) with the incorrect checksum from the script's working directory on the host (`InstallESD.dmg` on the guest is named `InstallESDDmg.pkg` on the host) and run the script again.

If the checksums match then I'm afraid I can't diagnose the issue; you could try to delete all the files from the script's working directory and try running it again.

**Comment by gzr58l** [comment]
I ran the commands above and found out that the InstallESD.dmg file had a different signature.  I removed it and re-ran the script.  It worked like a charm.

This is definitely the easiest approach to install MacOS.  Thank you so muhc for all your help
