### ISSUE TITLE
Unable to use script

### ISSUE THREAD

**Issue by ShadowGoat128134** [myspaghetti/macos-guest-virtualbox#138]
Maybe this is my own stupidity, but I believe I installed all the dependencies, but the script closes instantly upon me attempting to start it. Am I missing anything?

**Comment by myspaghetti** [comment]
If you're running Windows:
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
2. Install [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads)
3. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`, `wget`, and `unzip`
4. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
5. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash ./macos-guest-virtualbox.sh`)
