### ISSUE TITLE
VM fails to start when spaces exist in path name

### ISSUE THREAD

**Issue by koadman** [myspaghetti/macos-guest-virtualbox#139]
If the script is run in a directory that has spaces somewhere in its full path name the virtualbox VM will not start. A check for this and warning to the user might be helpful.

**Comment by myspaghetti** [comment]
Hi koadman! What version of the script are you using?

**Comment by myspaghetti** [comment]
Hi koadman!

* What version of the script are you using?
* What's the host OS?

**Comment by koadman** [comment]
it was a git clone of master as of today, 67a66cc. running on ubuntu 16.04 LTS and VirtualBox 6.0.14. I think it's a VirtualBox problem, not a problem with your script per se, because when I tried to launch the VM via the VirtualBox GUI I got the same error. The script worked well once I changed the path to eliminate the space!

**Comment by bhearsum** [comment]
This is still an issue, FYI. It would be great to re-open this to make it more visible. (I burnt a bunch of time on this...)

**Comment by myspaghetti** [comment]
@bhearsum is this is an issue with a VirtualBox version packaged with Ubuntu 16 LTS?

**Comment by bhearsum** [comment]
> @bhearsum is this is an issue with a VirtualBox version packaged with Ubuntu 16 LTS?

I don't think so. I'm running Ubuntu 23.04, and Virtualbox 7.0.6.

**Comment by myspaghetti** [comment]
Tested on Ubuntu 23.04 with VirtualBox 7.0.6, set VM name to "macOS with spaces", no issue.

Make sure the VM name parameter is set with single or double quotes: `vm_name="macOS with spaces"`
