### ISSUE TITLE
Crashes computer and unclear installation process

### ISSUE THREAD

**Issue by l-g** [myspaghetti/macos-guest-virtualbox#144]
Now the script seems to work (downloading worked fine) but there seems to be one other issue, somewhere along the installation the whole computer crashes/is force restarted.

First time I run the working script I did it through SSH and then I run unsupervised twice. All three times my brand new MBP16 crashed and restarted. The process was that I answered the first 3-4 prompts and then, when the downloading started, left the computer unsupervised. When I got back 5-10 minutes later it had restarted. Unfortunately, the terminal windows failed to restore so I don't know if there were any error messages or so displayed.

The fourth time I run the script (in terminal window 1) I redirected the output to a log file % `/opt/local/bin/bash macos-guest-virtualbox.sh > ~/Desktop/log` which I then `tail -f` (in terminal window 2). In W1 I responded to the prompts displayed in W2. Lo and behold, this time it didn't crash but completed as expected.

It feels very far fetched that terminal output would crash a computer but it happened three times in a row and the only thing I changed the last time was the redirection. I do have the log from the last, successful attempt if you are interested. I guess I also have the crash logs that I sent to Apple.

Furthermore, a UI-thing. The script restarts the VM at least three times. I didn't follow the details of what it was doing very carefully and I started to wonder if it had got stuck in some loop and was close to interrupting it. Maybe you could add a step counter in the script showing that it is making progress as expected? That is, if there are 20 prompts or so that the user should respond to, prepend every prompt with 1/20, 2/20, 3/20 and so on so the user knows that it is progressing as expected as well as gets an idea about how much is left.

**Comment by myspaghetti** [comment]
Considering you didn't follow the terminal and last time when `expr` failed you didn't bother mentioning it, I don't think it's a script issue that you didn't know what the script was doing. Maybe the steps could be described more at length in the welcome message.

macOS host issues with VirtualBox crashing the host are a known issue, you might want to report this to VirtualBox. The crash logs should tell you exactly if VirtualBox crashed.

Creating a log is a good idea, but that would require handling output on a much more intricate level: run everything at log verbosity (`wget`, `expr`, `csplit`, and so on) and then generate the terminal output that the user views. This is far too much for a script, that does not much except configure a virtual machine, download an installer, put it together, and run it.

**Comment by l-g** [comment]
What do you mean "and last time when `expr` failed you didn't bother mentioning it"?? I have included all information I had in my reports.
