### ISSUE TITLE
Line 99 single quote error

### ISSUE THREAD

**Issue by xaminmo** [myspaghetti/macos-guest-virtualbox#146]
On line 99 from 11 hours ago, there is a single quote added for posessive which breaks the rest of the script part of this commit: https://github.com/myspaghetti/macos-guest-virtualbox/commit/1c9fee0b1588bd4a55d80be3ed27349d2cc72dc8

**CURRENT**:
`temporary installation files and 15GB for the virtual machine's dynamically`

**CORRECT**:
`temporary installation files and 15GB for the virtual machine'\''s dynamically`

**Comment by myspaghetti** [comment]
Fixed!
