### ISSUE TITLE
Setting up missing serial number

### ISSUE THREAD

**Issue by abdulmanan7** [myspaghetti/macos-guest-virtualbox#148]
I want to confirm can I use the script to set my missing serial number on the actual MacBook pro 2014 model having Catalina installed.

My serial number is showed as unavailable and I want to set it up.
Please help if possible struggling from the last 1 month.
I have tried Blank board serializer download it write to USB and when I click EFI boot at the start of the machine it blanks and goes to login page like a normal reboot.

If this script provides any help it would be great because many people have same issue on the latest model and the old method of Blank board serializer not working.

**Comment by myspaghetti** [comment]
This is the wrong place to ask for support for third-party software that flashes your (bootleg? defective?) Macbook NVRAM.
