### ISSUE TITLE
Manual Steps needed to install

### ISSUE THREAD

**Issue by Lewiscowles1986** [myspaghetti/macos-guest-virtualbox#149]
I played about with this the other day and it does not work even from the release. It's quite clever sending input commands to the VM, but perhaps unnecessary as you can put scripts on the .viso if you want.

I put a `clear_input_buffer_then_read` before `# Detach the original 2GB BaseSystem.vdi` so that it would not detach the vdi until the disk was setup. Only After the disk is setup should the media be detached.

Once booted into the installer, it makes more sense to copy the efi after the install. This did not work using the scripts, so I terminated your script at this point, manually started the install using the GUI; then went to the terminal on reboot and copied the EFI files, NVRAM etc

With the efi files copied, I was able to shutdown, remove the install drive and the installation media and boot to the final installer.

Other notes are that the chipset should be `PIIX3`, the display should have 128MB VRAM + VMSVGA, usb should be `USB 3.0 (xHCI) Controller`

Thanks for sharing, it is still an incredibly cool tool, if only for the downloader and documentation of some steps

**Comment by myspaghetti** [comment]
Your comment is strange because:

* The VDI is not detached while in use, only after the VM is shut down.
* The EFI files are copied right after the installer app runs, there is no need to manually copy them.
* The USB controller is xHCI by default.
* The macOS will not boot with PIIX3, as far as I can tell.

**Comment by myspaghetti** [comment]
I removed the "manual NVRAM update" step from the script, there's no need to manually install these files this way.

**Comment by myspaghetti** [comment]
* The VDI does not detach while the VM is active, there's a wait loop.
* xHCI and 128MB VRAM is configured by default.
* PIIX3 is generally not recommended for macOS.

VMSVGA is much slower from my experience, and VBoxSVGA is faster than VBoxVGA, but for some reason VirtualBox shows a warning any graphics adapter other than VBoxVGA is selected.

The redundant NVRAM stage was removed, see version 0.83.1 for a working release.
