### ISSUE TITLE
Line 874: unexpected 'fi'

### ISSUE THREAD

**Issue by Arawn-Davies** [myspaghetti/macos-guest-virtualbox#151]
Just cloned this repo after wanting to make a new Mojave VM, after running it in cygwin  
(chmod +x done too) it gave this error

```
./macos-guest-virtualbox.sh: line 874: syntax error near unexpected token `fi'
./macos-guest-virtualbox.sh: line 874: `fi'
```
I opened it in nano, and saw an `fi` token but couldn't see a matching `if` or else if, so I commented   the last one out in that function, and it appears to be running again :)

**Comment by Arawn-Davies** [comment]
Should note I'm running latest bash on cygwin  
```
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
```

**Comment by myspaghetti** [comment]
Thanks! `fi`xed in master
