### ISSUE TITLE
Script shebang do no refer to default bash (macos issue)

### ISSUE THREAD

**Issue by brunomartinez-lmi** [myspaghetti/macos-guest-virtualbox#153]
The script shebang should be changed to `#!/usr/bin/env bash` instead of `#!/bin/bash`

This causes an issue on macos where the bash version /bin/bash is old and cannot be updated.
When installing more recent bash on macos and set it as default shell, `/usr/bin/env bash` gives the correct version whereas `/bin/bash` still points to the old bash.

I think it can also be an issue on linux for people having several bash versions installed.

**Comment by myspaghetti** [comment]
I'm conflicted about this. The script already checks what version of Bash it's running on, so in essence this is not an issue. `env` is definitely not the interpreter of the script so `#!/usr/bin/env` is kind of a [misstatement](https://www.in-ulm.de/~mascheck/various/shebang/#env). That said, using `env` both works and does what's expected, so there's no apparent downside other than being conceptually wrong.

**Comment by myspaghetti** [comment]
I'm gonna say the warning given by the script is sufficient. Closing as wontfix

**Comment by brunomartinez-lmi** [comment]
> I'm gonna say the warning given by the script is sufficient. Closing as wontfix

The warning is ok, but on macos the only way to have the script working is to modify the shebang because /bin/bash always refers to old bash version.

As you can see in this article (at the end of the article), changing the shebang is the only way in such shell script.
Moreover the shebang #/usr/bin/env is becoming a standard in shell scripts:
https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my

**Comment by myspaghetti** [comment]
>the only way to have the script working is to modify the shebang

...but the script works on macOS without modifying the shebang.

**Comment by brunomartinez-lmi** [comment]
> > the only way to have the script working is to modify the shebang
> 
> ...but the script works on macOS without modifying the shebang.

Indeed launching `/path-to-recent-bash/bash ./macos-guest-virtualbox.sh` works fine.
I just found it would be better to just launch `./macos-guest-virtualbox.sh` for macos users, for that reason I opened this issue, but I understand if you think this does not deserve a fix.

---

For example on my Mojave system with bash 5 installed, when cannot just launch `./macos-guest-virtualbox.sh`:

```
$ echo $BASH_VERSION
5.0.11(1)-release

$ ./macos-guest-virtualbox.sh
./macos-guest-virtualbox.sh: line 1032: -: syntax error: operand expected (error token is "-")
Please run this script on Bash 4.3 or higher.
macOS detected. Make sure the script is not running on
the default /bin/bash which is version 3.

)$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
