### ISSUE TITLE
Specifying individual script arguments doesn't work in Bash 5.0.11

### ISSUE THREAD

**Issue by khawkins** [myspaghetti/macos-guest-virtualbox#155]
The logic for parsing arguments (that aren't `documentation`) to the script doesn't work, at least in Bash 5.0.11.  The check:
```bash
[[ "${stages}" != *" ${argument} "* ]]
```
evaluates to "true" for any argument supplied.  This seems to be due to the fact that `stages` is defined with line-broken values.  If I change `stages` to a space-demarcated list of values, the issue goes away.

**Comment by myspaghetti** [comment]
Thanks! [Fixed in 0.85.3](https://github.com/myspaghetti/macos-guest-virtualbox/commit/e92563bc4d77587bd195288056779256489092a7). Also works by evaluating `${stages}` without quotes (as opposed to evaluating `"${stages}"`) but I guess it's better to be explicit.
