### ISSUE TITLE
./macos-guest-virtualbox.sh delete_temporary_files when guest machine is in saved state results in guest not starting

### ISSUE THREAD

**Issue by danieltomasz** [myspaghetti/macos-guest-virtualbox#159]
On Ubuntu 18.04 ( script version from yesterday early afternoon, I cannot tell which version exactly , becauce I updated it today) 
`/macos-guest-virtualbox.sh delete_temporary_files`
when guest machine is in saved state,  results in guest virtual machine not starting.

I cannot post any log more, since I delete guest machine and reinstalled guest machine.
(even the script informed me/gave me some warning that guest os is in save state, it was  proceeding anyway )

**Comment by myspaghetti** [comment]
Changed the warning to say "powered off" instead of "shut down" in [version 0.86.4](https://github.com/myspaghetti/macos-guest-virtualbox/commit/f0edf53fbc0e549c6750f8e62fdd628920328233)

**Comment by myspaghetti** [comment]
Corrected VM "powered off" detection in [version 0.86.5](https://github.com/myspaghetti/macos-guest-virtualbox/commit/ca347878ba006059020e960188fd636cca8952c7)
