### ISSUE TITLE
May I update to 10.15.3?

### ISSUE THREAD

**Issue by brauliobo** [myspaghetti/macos-guest-virtualbox#162]
macOS is asking for an update. Can I update or will it break the system?

![image](https://user-images.githubusercontent.com/41740/75061870-6600bd80-54c0-11ea-8069-94a771376b99.png)

**Comment by danieltomasz** [comment]
You could update, but only if you updated to the latest Virtualbox 6.1.4
I updated successfully yesterday my guest system :)

**Comment by brauliobo** [comment]
thanks @danieltomasz :) I'm using arch with 6.1.4, will update it now
