### ISSUE TITLE
One or more virtual storage files could not be loaded. Exiting.

### ISSUE THREAD

**Issue by panthersdude2001** [myspaghetti/macos-guest-virtualbox#167]
This error pops up when trying to populate the drive's installation disk
One or more virtual storage files could not be loaded. Exiting.
Is this a bug with the software?
I will try to run the software as an admin, and will report back.

**Comment by panthersdude2001** [comment]
I am giving up on High Sierra. It seems to be the files are broken.

**Comment by myspaghetti** [comment]
Hi. VirtualBox usually **can't** access the script's working directory and the files it generates if the script is run with elevated or "admin" privileges. If you ran Bash or the script with elevated privileges, VirtualBox will probably not be able to access the directory and the files until you fix their permissions or security policies, or start over in a directory accessible without elevated privileges.

Both VirtualBox and the script by design are not supposed to be run with elevated privileges.

**Comment by panthersdude2001** [comment]
Alright, thanks for confirming this as a bug.

**Comment by myspaghetti** [comment]
This isn't confirmed. You need to check which virtual storage file couldn't be attached to the virtual machine, and if it's a permissions issue or a file corruption issue or a different issue.

**Comment by myspaghetti** [comment]
This isn't confirmed. You need to check which virtual storage file couldn't be attached to the virtual machine, and if it's a permissions issue or a file corruption issue or a different issue. It's possible the script is working as intended.

Please report which storage devices are attached to the virtual machine.

**Comment by panthersdude2001** [comment]
Ok, got it to work thanks to running as admin, but now causing a Guru Meditation error in Vbox.
Storage devices are as follows:
Controller: SATA
SATA Port 0: Mac HS.vdi (Normal, 78.13 GB)

**Comment by myspaghetti** [comment]
>got it to work thanks to running as admin

You're just creating permissions issues. Does "got it to work" means macOS installed and boots into the setup and login screen? Or just that VirtualBox boots? I don't even know if you're still troubleshooting the bug or not.

**Comment by panthersdude2001** [comment]
It installed with the apple logo, went and rebooted and showed a black screen and then the Guru Meditation showed up with TRIPLE_FAULT

**Comment by myspaghetti** [comment]
Doesn't look like a script issue. You should check your VirtualBox configuration and file permissions, you should not run VirtualBox as admin and if you're seeing `VINF_EM_TRIPLE_FAULT` you might have a RAM configuration issue.

**Comment by panthersdude2001** [comment]
ok
