### ISSUE TITLE
Partitioning failed

### ISSUE THREAD

**Issue by ecatn** [myspaghetti/macos-guest-virtualbox#168]
Hi, firsttime VM start-up, and I got a ”wait for terminal is ready”, and I press enter lots of text outputs in terminal and enda with  Failed and in Install-script ”Iif partition failed ctrl-c,
any suggestions?

**Comment by myspaghetti** [comment]
Is the error message on the macOS guest Terminal [`/sbin/newfs_hfs failed with error 256 (resource busy)`](https://github.com/myspaghetti/macos-guest-virtualbox/issues/128)?

**Comment by myspaghetti** [comment]
Closing until further information is provided.

**Comment by weflower** [comment]
I just got the same, with the 256 error you mentioned.
