### ISSUE TITLE
Parameters / Configuration to Separate File

### ISSUE THREAD

**Issue by arrmo** [myspaghetti/macos-guest-virtualbox#170]
Hi,

First off - thanks! This works very well, thoroughly impressed. This is not a bug, just a potential enhancement suggestion.

To make it a bit easier to use, perhaps put the configuration / user modifable parameters in a separate (JSON?) file? And have the script read from that file? Just thinking that makes it a bit easier, but not a biggie.

Thanks again!

**Comment by myspaghetti** [comment]
Separating the executable from the configuration is unquestionably the correct design choice. The only reason I put the configuration together with the executable is so inexperienced users don't have to worry about multiple files - one and done.

It's trivial to fork the script so the `set_variables()` function is in its own file and then source it with `source variables.sh`

**Comment by myspaghetti** [comment]
Implemented separate file for configuration in [version 0.88.0](https://github.com/myspaghetti/macos-guest-virtualbox/commit/d027250a35b42f679c547f7430b0c793d173a801)

**Comment by arrmo** [comment]
Thanks! Just thinking it's easier for folks to change variables in one file, not mess with the core scripts.

Much appreciated!
