### ISSUE TITLE
board-id is (null)

### ISSUE THREAD

**Issue by arrmo** [myspaghetti/macos-guest-virtualbox#171]
Hi,

So close to getting everything working 😄. I had to restart from scratch, some FileVault related issues, but that's OK - gave me a chance to check things from the ground up. I am having one (small?) issue, hopefully this has been seen before, and there is a simple answer.

I have installed, with the script (variables) updated / set ... including as noted in #163 (thanks!). But I am finding that my BoardSerialNumber (checked by iMessageDebugv2) is (null). Not sure if there is an easy way to make this work? I do have it the script (DmiBoardSerial), but not working for some reason ... thoughts? I did remove the Apple ROM info from my VirtualBox config, perhaps that's needed? I removed because I'm not sure what to enter (1.23456 doesn't seem right ... LOL!) ... and supposedly VirtualBox will provide it's "internal EFI" version?

Also, FYI - I see System-ID as "failed", any thoughts on that one would be greatly appreciated also!

And one last question - hoping not to reinstall once this is figured out. From #62, it seems like the script can update values, vs. starting over ... is that right? Any info on that would be greatly appreciated.

Thanks!!!

**Comment by myspaghetti** [comment]
If you removed the Apple ROM info from the config then of course there would be no Apple ROM info. The board serial number is set in two places, the VirtualBox configuration and the virtual NVRAM. You need to run the EFI Internal Shell to load the NVRAM parameters. The documentation has all the details.

```
        iCloud and iMessage connectivity
iCloud, iMessage, and other connected Apple services require a valid device
name and serial number, board ID and serial number, and other genuine
(or genuine-like) Apple parameters. These parameters may be edited at the top
of the script or loaded through a configuration file as described in the
section above. Assigning these parameters is not required when installing or
running macOS, only when connecting to the iCould app, iMessage, and other
apps that authenticate the device with Apple.

These are the variables that are required for iMessage connectivity:

DmiSystemFamily    # Model name
DmiSystemProduct   # Model identifier
DmiSystemSerial    # System serial number
DmiSystemUuid      # Hardware UUID
DmiOEMVBoxVer      # Apple ROM info (major version)
DmiOEMVBoxRev      # Apple ROM info (revision)
DmiBIOSVersion     # Boot ROM version
DmiBoardProduct    # Main Logic Board identifier
DmiBoardSerial     # Main Logic Board serial (EFI)
MLB                # Main Logic Board serial (NVRAM)
ROM                # ROM identifier (NVRAM)
SYSTEM_UUID        # System identifier (NVRAM)

The comments at the top of the script specify how to view these variables
on a genuine Mac.

        Applying the EFI and NVRAM parameters
The EFI and NVRAM parameters may be set in the script before installation by
editing them at the top of the script, and applied after the last step of the
installation by resetting the virtual machine and booting into the
EFI Internal Shell. When resetting or powering up the VM, immediately press
Esc when the VirtualBox logo appears. This boots into the EFI Internal Shell or
the boot menu. If the boot menu appears, select "Boot Manager" and then
"EFI Internal Shell" and then allow the startup.nsh script to run
automatically, applying the EFI and NVRAM variables before booting macOS.
```

**Comment by arrmo** [comment]
First of all, thanks for the quick reply - so very much appreciated!

I did go in and update the ROM version. I was thinking it didn't matter, but it is key ... without that you don't get a BoardSerialNumber! May be something to note in the documentation later? Not a biggie though, just a thought.

I still seem to be missing two settings ... SmUUID (and I do have SYSTEM_UUID set), as well as System-ID. Any thoughts on those two? I don't see them in the documentation, but I may have missed it.

Also. your note about startup.nsh is very good. I admit, I wasn't aware of that. So is it the case that you can always edit the VirtualBox settings (.vbox), and new NVRAM will be built and applied by running startup.nsh? Just to understand. But it may be good to note this, if it's the case.

Thanks again!

**Comment by myspaghetti** [comment]
`system-id` is set with `SYSTEM_UUID # System identifier (NVRAM)`. Not sure what `SmUUID` is supposed to be, but iMessage works if you fill out all the parameters listed in the documentation.

**Comment by myspaghetti** [comment]
`system-id` is set with `SYSTEM_UUID # System identifier (NVRAM)`. Not sure what `SmUUID` is supposed to be, but iMessage works if you fill out all the parameters listed in the documentation.

Updating the NVRAM values after initial installation is covered in the documentation too:
```
        Changing the EFI and NVRAM parameters after installation
The variables mentioned above may be edited and applied to an existing macOS
virtual machine by executing the following command and copying the generated
files to the macOS EFI partition:

    ./macos-guest-virtualbox.sh \
configure_vm create_nvram_files create_macos_installation_files_viso

After running the command, attach the resulting VISO file to the virtual
machine's storage through VirtualBox Manager or VBoxManage. Power up the VM
and boot macOS, then start Terminal and execute the following commands, making
sure to replace "/Volumes/path/to/VISO/" with the correct path:

mkdir ESP
sudo su # this will prompt for a password
diskutil mount -mountPoint ESP disk0s1
cp -r /Volumes/path/to/VISO/ESP/* ESP/

After copying the files, boot into the EFI Internal Shell as desribed in the
section "Applying the EFI and NVRAM parameters".
```

**Comment by arrmo** [comment]
> `system-id` is set with `SYSTEM_UUID # System identifier (NVRAM)`. Not sure what `SmUUID` is supposed to be, but iMessage works if you fill out all the parameters listed in the documentation.

NP, will keep digging - thanks! FYI, SmUUID is noted here, https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/#TOP5. I admit, still trying to digest this myself ... LOL.

And appreciate the info on ESP!

**Comment by myspaghetti** [comment]
`smUUID` appears to be `MLB`

**Comment by arrmo** [comment]
Very well could be - too dang many new items ... LOL. I'm more of a Windows and Linux guy ... 😀 

Wondering why it's being detected as missing? Thinking there may be another VBox variable name. Will do some digging. Thanks!

**Comment by myspaghetti** [comment]
Sorry, the `smUUID` appears to be identical to `SYSTEM_UUID`, not what I wrote before.

**Comment by arrmo** [comment]
Yes, agreed! Still struggling to get smUUID set - even messing with plist (OpenCore), but no joy yet. Good though, I do have FileVault working, with OpenCore - just need to get the boot order updated (permanently) ... and the mouse when entering the boot password. Hmmm.

FYI, you may already know this, but big help in video speed with these two items - trying to share info!
https://superuser.com/questions/1403123/what-are-differences-between-vboxvga-vmsvga-and-vboxsvga-in-virtualbox
https://techsviewer.com/how-to-install-guest-tool-on-macos-virtualbox-with-128-mb-vram/

Seems odd, VMware driver in macOS, but works with the VMSVGA video. Just can't get the default to stick (even with that defaults command 😞).

Thanks!
