### ISSUE TITLE
Installer Exits Before downloading

### ISSUE THREAD

**Issue by koolade44** [myspaghetti/macos-guest-virtualbox#172]
I might be doing something wrong but:
I get this after hit enter once:
`vm_name="macOS"                  # name of the VirtualBox virtual machine
macOS_release_name="Catalina"    # install "HighSierra" "Mojave" or "Catalina"
storage_size=80000               # VM disk image size in MB. minimum 22000
cpu_count=2                      # VM CPU cores, minimum 2
memory_size=4096                 # VM RAM in MB, minimum 2048
gpu_vram=128                     # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution

These values may be customized as described in the documentation.

Press enter to continue, CTRL-C to exit.
`
The only option is ctrl-c and when i do this it closes the script

**Comment by myspaghetti** [comment]
Have you tried to `Press enter to continue`?

**Comment by myspaghetti** [comment]
Closing until further information is provided.
