### ISSUE TITLE
Virtualbox 6.1.4 script gets to initial boot to install and vm just restarts repeatedly

### ISSUE THREAD

**Issue by mschemerii** [myspaghetti/macos-guest-virtualbox#174]
Latest Windows 10 x64 update as of 13MAR2020
Virtualbox 6.1.4
Running from Ubuntu 18.04 WSL instance
All goes well until VirtualBox starts. Installation boots in a loop. I never get to the language selection.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. Please attach the following:

* The `VBox.log` file which [can be found in the virtual machine's directory](https://blogs.oracle.com/scoter/virtualbox-log-files-v2).
* The `md5sums.txt` file that results from the following command when run on the script's working directory: `find . -maxdepth 1 -type f -exec md5sum {} \; > md5sums.txt`

What sort of boot loop are you experiencing? Is there text? Does the Apple logo appear?

**Comment by mschemerii** [comment]
The apple logo never appears. I have attached a recording of the screen along with the VBox.log and md5sums.txt files.

[VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/4333059/VBox.log)
[recording.zip](https://github.com/myspaghetti/macos-guest-virtualbox/files/4333060/recording.zip)
[md5sums.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4333062/md5sums.txt)

**Comment by myspaghetti** [comment]
Thanks, greatly appreciate all the info.

Are you by any chance running VirtualBox that's installed on WSL?

**Comment by mschemerii** [comment]
Virtualbox is installed in Windows. Should I try Virtualbox in WSL?

**Comment by myspaghetti** [comment]
Nope, it's supposed to be on Windows. I'm asking because the boot is very strange. I'm looking into it.

**Comment by myspaghetti** [comment]
@mschemerii I think the boot fails because you've assigned 4GB of RAM to the virtual machine while you only have 3GB of RAM free. Try freeing more RAM or assigning 2GB of RAM for the virtual machine.

**Comment by mschemerii** [comment]
As I monitor the system, I show 6.4 of 7.7GB of memory free. I modified the script to set only 2GB of RAM for the VM. Same thing happens.
[VBox.log](https://github.com/myspaghetti/macos-guest-virtualbox/files/4333843/VBox.log)

**Comment by myspaghetti** [comment]
The log still shows less RAM available than assigned, but that might not be the issue.
```
00:00:03.864608 Host RAM: 7891MB (7.7GB) total, 1834MB available
00:00:04.796924   RamSize           <integer> = 0x0000000080000000 (2 147 483 648, 2 048 MB)
```
Another possibility is that macOS can't run on the virtualized AMD CPU. You can try applying one of these settings:
```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-2635QM"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i5-3570"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-5600U"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```
See if any one of these settings works, as suggested [here](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8#issuecomment-453847710).

I'm closing the issue because I'm unable to troubleshoot hardware or VirtualBox issues. The issue will remain unlocked so anyone can reply or reopen the issue if there's relevant information.

**Comment by weflower** [comment]
Just in case someone else comes here with the same issue, the first config setting you mentioned worked for me:
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"

I'm running Win10 on an i5-8250U laptop.
