### ISSUE TITLE
BaseSystem.vdi detaching

### ISSUE THREAD

**Issue by arrmo** [myspaghetti/macos-guest-virtualbox#175]
Hi,

I am trying a clean new install, but keep running in to this error,

```
If the partitioning fails, exit the script by pressing CTRL-C.
Otherwise, please wait.
Mojave_BaseSystem.vdi detached from the virtual machine
and released from VirtualBox Manager.

stage: populate_macos_target
One or more virtual storage files could not be loaded. Exiting.
```

Thoughts?

Thanks!

**Comment by myspaghetti** [comment]
`BaseSystem.vdi` is supposed to detach so the system can boot from the populated installer volume. See the VirtualBox storage manager for which virtual storage files could not be loaded. This may be a permissions issue or some other file access issue.

**Comment by arrmo** [comment]
Did a full clean, reboot, retry - then OK. Sorry for the hassle!
