### ISSUE TITLE
Mojave can not boot in windows 10 WSL

### ISSUE THREAD

**Issue by mwylaoma** [myspaghetti/macos-guest-virtualbox#176]
I install Mojave with WSL in windows 10 . But can not boot.
![1](https://user-images.githubusercontent.com/3048280/76829210-976d6e80-685d-11ea-8017-dfb46eced9ba.png)

**Comment by myspaghetti** [comment]
Could not reproduce. The latest version of the Mojave Base System (041-88800) boots correctly under the latest release version of VirtualBox 6.1.4 with the latest release version of Windows 10 18363.720 with Ubuntu over WSL1.

**Comment by myspaghetti** [comment]
Are you by any chance using WSL2?

**Comment by mwylaoma** [comment]
No，I use the same version of Windows 10 and with Ubuntu over WSL1

**Comment by mwylaoma** [comment]
But，I change the cpu profile
`VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"`
It works.
But It sucks at 
```
Partitioning the target virtual disk and the installer virtual disk.
Loading base system onto the installer virtual disk. Moving installation
files to installer virtual disk, updating InstallInfo.plist, and rebooting the
virtual machine.

The virtual machine may report that disk space is critically low; this is fine.        
When the installer virtual disk is finished being populated, the script will
shut down the virtual machine. After shutdown, the initial base system will be
detached from the VM and released from VirtualBox.

If the partitioning fails, exit the script by pressing CTRL-C.
Otherwise, please wait.
```

**Comment by myspaghetti** [comment]
Is the virtual machine partitioning the virtual drives?

**Comment by mwylaoma** [comment]
Maybe，I will screenshot it
