### ISSUE TITLE
Always Errors on Could not configure virtual machine storage controller. Exiting

### ISSUE THREAD

**Issue by GhostBassist** [myspaghetti/macos-guest-virtualbox#180]
```
function populate_virtual_disks() {
print_dimly "stage: populate_virtual_disks"
# Attach virtual disk images of the base system, installation, and target
# to the virtual machine
VBoxManage storagectl "${vm_name}" --remove --name SATA >/dev/null 2>&1
if [[ -n $(
    2>&1 VBoxManage storagectl "${vm_name}" --add sata --name SATA --hostiocache on >/dev/null
) ]]; then
    echo "Could not configure virtual machine storage controller. Exiting."; exit
```
Cannot be Actioned whilst VM is Running - Had to manually stop the VM, Comment out Initial Steps and Run script starting at function populate_mac_os_target() to get to work

**Comment by myspaghetti** [comment]
How is your virtual machine running if the script hasn't started it yet?

**Comment by GhostBassist** [comment]
This is after the first run through before it loads the 2x terminal windows.

**Comment by myspaghetti** [comment]
The script doesn't start the VM anywhere prior to `populate_virtual_disks`. The script warns the user if a virtual machine already exists at `prompt_delete_existing_vm`. The script exits if `create_vm` fails.

You must manually bypass those steps to get to `populate_virtual_disks` with a running VM.

**Comment by myspaghetti** [comment]
The script doesn't start the VM anywhere prior to `populate_virtual_disks`. The script warns the user if a virtual machine already exists at `prompt_delete_existing_vm`. The script exits if `create_vm` fails:
```
Error: Could not create virtual machine "macOS".
Please delete exising "macOS" VirtualBox configuration files manually.

Error message:
VBoxManage.exe: error: Machine settings file 'C:\Users\Jack\VirtualBox VMs\macOS
\macOS.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
achineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.
raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), mac
hine.asOutParam())" at line 280 of file VBoxManageMisc.cpp
```

You must manually bypass those steps to get to `populate_virtual_disks` with a running VM.

**Comment by myspaghetti** [comment]
The script doesn't start the VM anywhere prior to `populate_virtual_disks`. The script warns the user if a virtual machine already exists at `prompt_delete_existing_vm`. The script exits if `create_vm` fails:
```
Error: Could not create virtual machine "macOS".
Please delete exising "macOS" VirtualBox configuration files manually.

Error message:
VBoxManage.exe: error: Machine settings file 'C:\Users\Jack\VirtualBox VMs\macOS
\macOS.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
achineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.
raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), mac
hine.asOutParam())" at line 280 of file VBoxManageMisc.cpp
```

You must manually bypass those steps to get to `populate_virtual_disks` with a running VM, so if you got there you had to do some non-trivial steps to bypass the warnings and break the script.

**Comment by myspaghetti** [comment]
The script doesn't start the VM anywhere prior to `populate_virtual_disks`. The script warns the user if a virtual machine already exists at `prompt_delete_existing_vm`. The script exits if `create_vm` fails:
```
Error: Could not create virtual machine "macOS".
Please delete exising "macOS" VirtualBox configuration files manually.

Error message:
VBoxManage.exe: error: Machine settings file 'C:\Users\Jack\VirtualBox VMs\macOS
\macOS.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
achineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.
raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), mac
hine.asOutParam())" at line 280 of file VBoxManageMisc.cpp
```

If you got to `populate_virtual_disks` with a running VM you had to perform some non-trivial steps to bypass the warnings and break the script.

**Comment by GhostBassist** [comment]
Apologies Jack,
My fault for not explaining correctly.

it appears to be Running the Populate Virtual Disks method fine.
after it runs through the partitioning, and tries to release the basesystem vdi its not completing as the VM is still running. causing the script to break and stop.
i had to manually stop the VM,
and then re run the script, starting from the populate_macos_target() method.

happy to set up a screenshare and show you what is happening if needs be

**Comment by myspaghetti** [comment]
If the `populate_virtual_disks` stage fails then the virtual machine won't power off. The following commands should execute in the virtual machine's Terminal:
```
disks="$(diskutil list | grep -o "\*[0-9][^ ]* GB *disk[0-9]$" | grep -o "[0-9].*" | sort -gr | grep -o disk[0-9] )" \
&& disks=(${disks[@]}) \
&& if [ -z "${disks}" ]; then echo "Could not find disks"; fi \
&& [ -n "${disks[0]}" ] && diskutil partitionDisk "/dev/${disks[0]}" 1 GPT APFS "" R \
&& diskutil partitionDisk "/dev/${disks[1]}" 1 GPT JHFS+ "Install" R \
&& asr restore --source "/Volumes/Mojav-files/BaseSystem.dmg" --target /Volumes/Install --erase --noprompt \
&& app_path="$(ls -d "/Volumes/"*"Base System 1/Install"*.app)" \
&& install_path="${app_path}/Contents/SharedSupport/" \
&& mkdir -p "${install_path}" && cd "/Volumes/Mojav-files/" \
&& cp *.chunklist *.plist *.dmg "${install_path}" && echo "" \
&& echo "Copying the several-GB InstallESD.dmg to the installer app directory" \
&& echo "Please wait" && if [ -s "${install_path}/InstallESD.dmg" ]; then rm -f "${install_path}/InstallESD.dmg" ; fi \
&& for part in InstallESD.part*; do echo "Concatenating ${part}"; cat "${part}" >> "${install_path}/InstallESD.dmg"; done \
&& sed -i.bak -e "s/InstallESDDmg\.pkg/InstallESD.dmg/" -e "s/pkg\.InstallESDDmg/dmg.InstallESD/" "${install_path}InstallInfo.plist" \
&& sed -i.bak2 -e "/InstallESD\.dmg/{n;N;N;N;d;}" "${install_path}InstallInfo.plist" \
&& shutdown -h now
```
If any of these commands do not return successfully, then `shutdown -h now` will not execute. However, if `populate_macos_target` succeeded, then all of the commands above must have succeeded, except `shutdown -h now`

At any rate I'll add a check that the VM is powered off at the start of `populate_macos_target`

**Comment by myspaghetti** [comment]
...never mind, there's already one there:
```
if [[ "$( VBoxManage list runningvms )" =~ \""${vm_name}"\" ]]; then
    printf "${highlight_color}"'Please '"${warning_color}"'manually'"${highlight_color}"' shut down the virtual machine and press enter to continue.'"${default_color}"
    clear_input_buffer_then_read
fi
```
