### ISSUE TITLE
Install script in OS is only compatible with english language

### ISSUE THREAD

**Issue by FellFromTheSky** [myspaghetti/macos-guest-virtualbox#185]
I had to retry to install macOS trough this script like 5 times because I didn't know itwas only compatible with english language. Also, it doesn't say you when to press Enter (after or before the window is clicked by the user).
Please fix this and make a tutorial.
Thanks.

**Comment by myspaghetti** [comment]
[Added a warning in version 0.88.8](https://github.com/myspaghetti/macos-guest-virtualbox/commit/350838e0b0399ca4dc1f80b0d0a7072b77d6839a).
