### ISSUE TITLE
VirtualBox guest additions or not?

### ISSUE THREAD

**Issue by morgansimonsen** [myspaghetti/macos-guest-virtualbox#187]
Hi. What is the recommendation regarding the VirtualBox additions with this script? What, if any, performance increase can be expected? Are there any known problems? Will installing them break iMessage?

M

**Comment by myspaghetti** [comment]
>What is the recommendation regarding the VirtualBox additions with this script?

[https://github.com/myspaghetti/macos-guest-virtualbox#dependencies](https://github.com/myspaghetti/macos-guest-virtualbox#dependencies): VirtualBox≥6.0 with Extension Pack

>What, if any, performance increase can be expected?

The Extension Pack is exclusively used for USB support, which is not necessary but often requested.

>Are there any known problems?

Yes, USB support behaves unexpectedly, including disconnects and failure to connect some devices.

>Will installing them break iMessage?

Extension Pack has no effect on iMessage.

**Comment by morgansimonsen** [comment]
Thanks but my question was about the additions pack you install inside the guest OS, not the extensions pack that adds more features to the virtualization host. Additions can be installed by selecting "Insert VirtualBox image" on the VM window and then installing the dpkg in macOS. This, among other things, enable cut/past between the host and guest.

**Comment by myspaghetti** [comment]
VirtualBox Guest Additions work but don't offer any performance improvements. They don't conflict with iMessage either. For graphics performance improvements you can install [VMware Tools](https://my.vmware.com/web/vmware/details?downloadGroup=VMTOOLS1100&productId=742) in VirtualBox. Better performance improvements are available by importing the virtual machine into VMWare or Parallels, but either option is similar to VirtualBox performance except for graphics. KVM on Linux offers near-native performance but it's more complicated to configure.

**Comment by morgansimonsen** [comment]
VMWarw tools in Virtual box, really? How does that work, how can VMWare drivers plug into acceleration features in VBox?

I saw the comment in your readme about transferring the machine to KVM and thought that sounded very interesting. Do you have any information on how to do that?

**Comment by myspaghetti** [comment]
The VMWare macOS graphics driver works in VirtualBox, the same way an open-source audio driver like AppleALC works on VirtualBox. VirtualBox virtualizes the hardware (a video or audio device) and the driver connects between macOS and the virtual hardware.

There's [this tutorial for KVM passthrough](https://passthroughpo.st/mac-os-vm-guide-part-2-gpu-passthrough-and-tweaks/) but it's outdated and uses Clover instead of OpenCore. The basics are the same, getting it to work on your device will require a lot of manual configuration.

**Comment by myspaghetti** [comment]
The new [VMWare Tools 11.0.6](https://my.vmware.com/web/vmware/details?downloadGroup=VMTOOLS1106&productId=973) installer is notarized so it's even easier to install.
