### ISSUE TITLE
Additional information needed in the main README file

### ISSUE THREAD

**Issue by JFLarvoire** [myspaghetti/macos-guest-virtualbox#188]
Hello,

Thanks for sharing this script, I finally succeeded in creating a MacOS VM!  
However, I first got caught in a trap that had already been reported by others. Ex: Bug #140  
I now see that the information was provided in the console, but this is not sufficient: As the script progress was quite slow, I kept moving to other tasks after pressing Enter each time. And when I saw the MacOS installation prompt, I thought the script had completed.

Please update the main README.md file, in the very first section:  
After the paragraph beginning with "The script requires very little user interaction", add another one saying something like:  
"Important: Do not respond to MacOS installation prompts yourself. Every time there's a prompt, come back to the script, and press Enter to let it continue the automated configuration itself."

**Comment by myspaghetti** [comment]
Sure, I'll add an explicit warning.

**Comment by myspaghetti** [comment]
Added a warning in version 0.89.7
