### ISSUE TITLE
stage: error I encountered in populate_virtual_disks

### ISSUE THREAD

**Issue by nahita** [myspaghetti/macos-guest-virtualbox#189]
Hello, first of all thank you for your effort. This is the first time I use github. My English is not good. I encountered a problem. I would be glad if you could help.

 The idea of ​​this script is very nice. I thought I would do the difficult process like installing Macos with a single click, but unfortunately I encountered problems. Although I have tried several times, I am encountering this problem. What do I do? necessary. I am using Ubuntu 18.04, virtualbox 6.1.4. Guest plugins are installed.

`
........
Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   470KB/s    kalan 10m 11Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   476KB/s    kalan 10m 10Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   496KB/s    kalan 10m 10Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   503KB/s    kalan 10m 10Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   516KB/s    kalan 10m 10Mojave_InstallESDDm  92%[+++++++==========>  ]   4,77G   529KB/s    kalan 10m 10Mojave_InstallESDDm  99%[+++++++===========> ]   5,15G   612KB/s    kalan 0s   ./macos-guest-virtualbox.sh: satır 440: 21164 Parçalama arızası    (çekirdek döküldü) wget "${urlbase}${filename}" ${wgetargs} --output-document "${macOS_release_name}_${filename}"

Splitting the several-GB InstallESDDmg.pkg into 1GB parts because
VirtualBox hasn't implemented UDF/HFS VISO support yet and macOS
doesn't support ISO 9660 Level 3 with files larger than 2GB.
'Mojave_InstallESD.part00' dosyası oluşturuluyor
'Mojave_InstallESD.part01' dosyası oluşturuluyor
'Mojave_InstallESD.part02' dosyası oluşturuluyor
'Mojave_InstallESD.part03' dosyası oluşturuluyor
'Mojave_InstallESD.part04' dosyası oluşturuluyor
'Mojave_InstallESD.part05' dosyası oluşturuluyor

stage: create_nvram_files

stage: create_macos_installation_files_viso
Creating EFI startup script

Creating VirtualBox 6 virtual ISO containing the
installation files from swcdn.apple.com

stage: create_basesystem_vdi
Converting to BaseSystem.dmg to BaseSystem.img

dmg2img v1.6.7 (c) vu1tur (to@vu1tur.eu.org)

Mojave_BaseSystem.dmg --> Mojave_BaseSystem.img

decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...              93.12%ERROR: Inflation failed
Converting from raw image file="Mojave_BaseSystem.img" to file="Mojave_BaseSystem.vdi"...
Creating dynamic image with size 1872206887 bytes (1786MB)...
VBoxManage: error: VD: The given disk size 1872206887 is not aligned on a sector boundary (512 bytes)
VBoxManage: error: Error code VERR_VD_INVALID_SIZE at /home/vbox/vbox-6.1.6/src/VBox/Storage/VD.cpp(6242) in function int VDCreateBase(PVDISK, const char*, const char*, uint64_t, unsigned int, const char*, PCVDGEOMETRY, PCVDGEOMETRY, PCRTUUID, unsigned int, PVDINTERFACE, PVDINTERFACE)
VBoxManage: error: Cannot create the disk image "Mojave_BaseSystem.vdi": VERR_VD_INVALID_SIZE

stage: create_target_vdi
Creating macOSMojave target system virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 503f76f7-f4ff-423a-8bd4-28a46074cd28

stage: create_install_vdi
Creating Mojave installation media virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 7e203170-88e1-4fad-8206-13240c4f62c1

stage: configure_vm

stage: populate_virtual_disks
Could not attach "Mojave_BaseSystem.vdi". Exiting.
mono@mono-K52JT:~/Masaüstü/mac$ 
![2020-04-20 00-19-11 ekran görüntüsü2](https://user-images.githubusercontent.com/10479148/79700283-41954780-829d-11ea-9bf2-2bb3b63501c3.png)
` #

**Comment by myspaghetti** [comment]
Hi, thanks for the detailed bug report! `dmg2img` failed to convert `Mojave_BaseSystem.dmg` to `Mojave_BaseSystem.img`.

If you want to troubleshoot the issue please run `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt` and post the resulting `troubleshoot.txt` here, or you could just try running the script again after deleting `Mojave_BaseSystem.img` which might have failed to download correctly.

**Comment by myspaghetti** [comment]
You've also had a core dump while running `wget` (`Parçalama arızası (çekirdek döküldü)`) so you should probably update your version of `wget` or your kernel.

**Comment by nahita** [comment]
troubleshoot.txt

`#!/bin/bash
# Push-button installer of macOS on VirtualBox
# (c) myspaghetti, licensed under GPL2.0 or higher
# url: https://github.com/myspaghetti/macos-guest-virtualbox
# version 0.89.9
################################################################################
BASH_VERSION 4.4.20(1)-release
VBOX_VERSION 6.1.6r137129
OS VERSION 5.3.0-45-generic
################################################################################
vbox.log
VBoxManage: error: Could not open log file '/home/mono/VirtualBox VMs/macOSMojave/Logs/VBox.log' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "ReadLog(uLogIdx, uOffset, _1M, ComSafeArrayAsOutParam(aLogData))" at line 2718 of file VBoxManageInfo.cpp
################################################################################
vminfo
name="macOSMojave"
groups="/"
ostype="macOS 10.13 High Sierra (64-bit)"
UUID="42525145-0437-413e-8248-681548d41918"
CfgFile="/home/mono/VirtualBox VMs/macOSMojave/macOSMojave.vbox"
SnapFldr="/home/mono/VirtualBox VMs/macOSMojave/Snapshots"
LogFldr="/home/mono/VirtualBox VMs/macOSMojave/Logs"
hardwareuuid="42525145-0437-413e-8248-681548d41918"
memory=2048
pagefusion="off"
vram=128
cpuexecutioncap=100
hpet="off"
cpu-profile="host"
chipset="ich9"
firmware="EFI"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="none"
boot2="none"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
BIOS NVRAM File="/home/mono/VirtualBox VMs/macOSMojave/macOSMojave.nvram"
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="off"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="minimal"
VMState="poweroff"
VMStateChangeTime="2020-04-19T21:49:45.000000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="none"
"SATA-1-0"="none"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800273B3DBF"
cableconnected1="on"
nic1="nat"
nictype1="82545EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
nic9="none"
nic10="none"
nic11="none"
nic12="none"
nic13="none"
nic14="none"
nic15="none"
nic16="none"
nic17="none"
nic18="none"
nic19="none"
nic20="none"
nic21="none"
nic22="none"
nic23="none"
nic24="none"
nic25="none"
nic26="none"
nic27="none"
nic28="none"
nic29="none"
nic30="none"
nic31="none"
nic32="none"
nic33="none"
nic34="none"
nic35="none"
nic36="none"
hidpointing="usbtablet"
hidkeyboard="usbkbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="on"
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="/home/mono/VirtualBox VMs/macOSMojave/macOSMojave.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
Key: VBoxInternal/Devices/efi/0/Config/DmiBIOSVersion, Value: string:MBP7.89
Key: VBoxInternal/Devices/efi/0/Config/DmiBoardProduct, Value: Mac-3CBD00234E554E41
Key: VBoxInternal/Devices/efi/0/Config/DmiBoardSerial, Value: NO_LOGIC_BOARD_SN
Key: VBoxInternal/Devices/efi/0/Config/DmiOEMVBoxRev, Value: string:.23456
Key: VBoxInternal/Devices/efi/0/Config/DmiOEMVBoxVer, Value: string:1
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemFamily, Value: MacBook Pro
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemProduct, Value: MacBookPro11,2
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemSerial, Value: NO_DEVICE_SN
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemUuid, Value: CAFECAFE-CAFE-CAFE-CAFE-DECAFFDECAFF
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemVendor, Value: Apple Inc.
Key: VBoxInternal/Devices/efi/0/Config/DmiSystemVersion, Value: 1.0
Key: VBoxInternal/Devices/smc/0/Config/DeviceKey, Value: ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc
Key: VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC, Value: 0
Key: VBoxInternal2/EfiGraphicsResolution, Value: 1366x768
################################################################################
md5 hashes
ce2c02a6669dd02d830a97afc285ce17  Mojave_BaseSystem.chunklist
9a8147c45fe55e574efba47027fe0750  Mojave_BaseSystem.dmg
2c87d0cba59fc948441df95410af3865  Mojave_BaseSystem.img
294d9410b79228061faf15bf398f5c84  Mojave_Installation_files.viso
3ffc64e9a5fd3d1cb65314432c3b1c53  Mojave_InstallESDDmg.pkg
dbf6d95266beefc887a38c63a7df383a  Mojave_InstallESD.part00
1b5c60cd12a10eacb692f3d36f8046e7  Mojave_InstallESD.part01
4a3613e31816afc5a750f0c461a54c99  Mojave_InstallESD.part02
86e61d1dd0ed054e00d4d49ca5bd84f7  Mojave_InstallESD.part03
e84ab943b9a57a11491ddff9483ac0b3  Mojave_InstallESD.part04
1d9f2a2a3bbb9d88b15f0114aed56d7d  Mojave_InstallESD.part05`

**Comment by myspaghetti** [comment]
Yup the download failed, the files are corrupt. These are the correct MD5 hashes:
```
b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
137a58cf2f9497b0800f775d31edfcc8 *Mojave_InstallESDDmg.pkg
```

Update the kernel or `wget`, delete all the downloaded files and try again.

**Comment by nahita** [comment]
Hello, I reinstalled the operating system. I upgraded the Linux kernel to 5.6. I uninstalled wget, installed it again, but nothing has changed. Is there a link to download the Mojave_BaseSystem.dmg and * Mojave_InstallESDDmg.pkg files directly? Let me download it from there.

**Comment by nahita** [comment]
today I installed the 19.10 version of ubunt as a clean installation. I installed the dependencies. The wget tool is a higher version than 18.04. Nevertheless, I uninstalled wget and reinstalled it. But still I get an error. The error is as if the file was downloaded.

**Comment by myspaghetti** [comment]
If you're still getting a segmentation fault when running `wget` (`Parçalama arızası (çekirdek döküldü)`) there's nothing I can do. This is not an issue with the script.
