### ISSUE TITLE
RTR3InitEx failed with rc=-1912 (rc=-1912)

### ISSUE THREAD

**Issue by alessandromichelazzi** [myspaghetti/macos-guest-virtualbox#191]
I am getting this message:

"The VirtualBox kernel modules do not match this version of VirtualBox. The installation of VirtualBox was apparently not successful. Executing

'/sbin/vboxconfig'

may correct this. Make sure that you are not mixing builds of VirtualBox from different sources.

where: supR3HardenedMainInitRuntime what: 4 VERR_VM_DRIVER_VERSION_MISMATCH (-1912) - The installed support driver doesn't match the version of the user. "

Looking online seams to be an error of different versions of Virtual Box installed. I've tried to remove and again re-install Virtual Box at the last actual version (6.1.6) but I still get this message. 

Any suggestion? Using Ubuntu 19.10

**Comment by myspaghetti** [comment]
This is a host kernel issue, you need to install VirtualBox with the proper kernel modules. Install VirtualBox from the system's package manager and follow the package manager's instructions about installing the kernel modules, if any.

**Comment by niknak88** [comment]
I have the same error, and like alessandromichelazzi, I have the same ubuntu version.

If I try to install VirtualBox from the system's package manager, Ubuntu install me an old version of VirtualBox (5.2.34).

Any help for clean install ?

**Comment by myspaghetti** [comment]
[You need to install VirtualBox with the proper kernel modules. Install VirtualBox from the system's package manager and follow the package manager's instructions about installing the kernel modules.](https://askubuntu.com/questions/1222912/virtualbox-kernel-vboxdrv-not-loaded-on-ubuntu-19-10)
