### ISSUE TITLE
Information on how to generate serial numbers/UUID etc would be helpful. iMessage/FaceTime login fails :(

### ISSUE THREAD

**Issue by segdy** [myspaghetti/macos-guest-virtualbox#192]
It would be super helpful to have a bit more information on the purpose/meaning of the variables and, if necessary, how to generate them:
`DmiSystemFamily, DmiSystemProduct, DmiSystemSerial, DmiSystemUuid, DmiOEMVBoxVer, DmiOEMVBoxRev, DmiBIOSVersion, DmiBoardProduct, DmiBoardSerial, MLB, ROM, SYSTEM_UUID`

I tried to be careful with as much as I could guess and used uuidgen to generate DmiSystemUuid and SYSTEM_UUID. I also used macserial32.exe to generate DmiSystemSerial, DmiBoardSerial and MLB (with `--mlb` switch).

However, login into iMessage and FaceTime still fails with "Could not sign in to iMessage: Could not sign in. Please check your network connection and try again" and "An error occured during authentication". 
I do get the authentication request on my phone though which I accept and I get a PIN which I enter correctly. Yet, the error still occurs.

More information on this topic would be super helpful!!
(Otherwise this script is truly amazing!)

**Comment by myspaghetti** [comment]
Sorry, information about running macOS on non-Apple devices will not be provided. The script tells you exactly how to get the genuine information off a genuine Apple device. For legal reasons the script only supports genuine Apple devices.
