### ISSUE TITLE
Bash-5.0 "Please run this script on Bash 4.3 or higher"

### ISSUE THREAD

**Issue by brentonv** [myspaghetti/macos-guest-virtualbox#193]
This looks great but having trouble on Mojave.

> `Last login: Thu Apr 23 21:59:18 on ttys000
Brentons-MacBook-Pro:~ brenton$ cd Desktop/
Brentons-MacBook-Pro:Desktop brenton$ ls
macos-guest-virtualbox.sh	volume(sda1)
Brentons-MacBook-Pro:Desktop brenton$ ./macos-guest-virtualbox.sh 
Please run this script on Bash 4.3 or higher.
macOS detected. Make sure the script is not running on
the default /bin/bash which is version 3.
Brentons-MacBook-Pro:Desktop brenton$ bash --version
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin18.7.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

Please advise,
Thanks

**Comment by myspaghetti** [comment]
>`macOS detected. Make sure the script is not running on the default /bin/bash which is version 3.`

This means you have to run the script with `/path/to/bash5 ./macos-guest-virtualbox.sh`

**Comment by brentonv** [comment]
Thanks @myspaghetti 

> `$ which -a bash
/usr/local/bin/bash
/bin/bash`

That fixed it.
