### ISSUE TITLE
Is there a way to change the resolution after creating the VM?

### ISSUE THREAD

**Issue by aidenmitchell** [myspaghetti/macos-guest-virtualbox#194]

**Comment by myspaghetti** [comment]
VBoxManage setextradata "${vm_name}" "VBoxInternal2/EfiGraphicsResolution" "${resolution}"

**Comment by myspaghetti** [comment]
`VBoxManage setextradata "${vm_name}" "VBoxInternal2/EfiGraphicsResolution" "${resolution}"`

**Comment by aidenmitchell** [comment]
Great, thank you.

**Comment by aidenmitchell** [comment]
So, it seems to work during boot but then the screen goes fuzzy and it returns to 1024x768. I'll try re-creating the VM with the proper settings.

**Comment by myspaghetti** [comment]
These are the primary display resolutions supported by macOS on VirtualBox: `5120x2880` `2880x1800` `2560x1600` `2560x1440` `1920x1200` `1600x1200` `1680x1050` `1440x900` `1280x800` `1024x768` and `640x480`

`1024x768` and `640x480` are not recommended. Secondary displays can have an arbitrary resolution.

**Comment by aidenmitchell** [comment]
Ok, thank you. I believe the problem is the VMware Tools I installed on the guest to facilitate the mouse cursor integration. It keeps setting it back.
