### ISSUE TITLE
(Question) EFI folder on VirtualBox 6.1.x

### ISSUE THREAD

**Issue by brentonv** [myspaghetti/macos-guest-virtualbox#195]
Firstly a big thanks to you guys for creating this script it's really quite amazing. I've used your script and it works great but just a question about the efi folder. I have previously experimented with different installs and also without your script and since VirtualBox 6.1.x I can't seem to boot from the efi folder.

I have previously used refind on 6.0.x but since 6.1.x VirtualBox has apfs support and it seems to bypass the efi folder and I can no longer boot to refind so I would also assume this is the same with your oc folder.

Is this correct or am I missing something with booting the efi folder?

**Comment by myspaghetti** [comment]
Yes, you're correct, VirtualBox 6.1 doesn't run the EFI Internal Shell `startup.nsh` script by default because it finds and boots macOS first. If you drop to the EFI Internal Shell it'll execute `startup.nsh` and boot what you like. You can also set the boot executable in NVRAM, but it will likely get overwritten by macOS when it boots.

**Comment by brentonv** [comment]
So is the only way to boot into recovery by scripting it in startup.nsh?

**Comment by myspaghetti** [comment]
You can use OpenCore, which respects NVRAM boot options; or you can manually boot into recovery from the EFI Internal Shell; or you can script it in `startup.nsh`; or you could probably use rEFInd to boot into recovery, but I haven't used it in a long time so I'm not certain.

**Comment by brentonv** [comment]
Thanks. I tried booting EFI internal shell and it also skipped the EFI folder. The only option seems to be run a boot command or use startup.nsh

**Comment by kromanovs** [comment]
>So is the only way to boot into recovery by scripting it in startup.nsh?
I was able to boot into recovery by entering the bios (Esc on VM startup), then Boot from File - and there you can select efi from Recovery volume.
