### ISSUE TITLE
ZSH check corrections (and some other things)

### ISSUE THREAD

**Issue by thibpoullain** [myspaghetti/macos-guest-virtualbox#196]
Hi, 

I'm on Catalina 10.15.3 and ZSH 5.7

```
echo $ZSH_VERSION
5.7.1
```

## The zsh version env var

I have the error : 

`Can't determine ZSH_VERSION. Exiting.`

But my ZSH_VERSION is set to 5.7.1 (Checked with echo).

So I've modified the script as the above :

```
if [[ $ZSH_VERSION ]]; then
```

instead of 

```
if [[ -z "${ZSH_VERSION}" ]]; then
```

And it works.

## The zsh version number check

I have the error : 

`Please run this script on zsh 5 or higher.`

I still don't understand because I've tested it in my terminal :

```
if [[ "${ZSH_VERSION:0:1}" -lt 5 ]]; then
echo 'it is true'
else
echo 'it is false'
fi

>> it is false
```

So it should works...

I'll bypass this test for my case. But if it could help to improve the script, I'm all yours ;)

## line 132: setopt: command not found

But`setopt` is present on my system. When I type it I got : 

```
$ setopt
combiningchars
interactive
login
monitor
promptsubst
shinstdin
zle
```
It does'nt prevent the script to going on.

**Comment by myspaghetti** [comment]
You're running the script on zsh with `/bin/bash`. Edit the shebang to say `#!/bin/zsh` before running on zsh.

**Comment by thibpoullain** [comment]
Damned... I went too fast...

**Comment by myspaghetti** [comment]
Additionally, I suspect either `csplit` or `gzip` are not the GNU variant even though it's available on macOS by default. The script breaks if they're not the GNU variant.

I'll fix the zsh check in the next version.

**Comment by myspaghetti** [comment]
Not fixed, but the error message is more informative in [0.90.2](https://github.com/myspaghetti/macos-guest-virtualbox/commit/cdd1893a31d0d9c83fa182f2ca92d59d1615095e)

**Comment by thibpoullain** [comment]
I don't know about the GNU variant of the package but it works out of the box.
The screen is not at the right resolution, I only see the quarter of the content of the VM.
