### ISSUE TITLE
Apple keyboard 

### ISSUE THREAD

**Issue by thibpoullain** [myspaghetti/macos-guest-virtualbox#198]
Hi, It's not an issue but I've nowhere to ask but here ;)
I'm already on mac, and there is only a PC keyboard installed on the VM. 
Obviously I searched on the internet how to add a mac keyboard on.. a mac, hard question lol
thx

**Comment by myspaghetti** [comment]
There are no keyboard configuration options for VirtualBox. The guest always sees a PS/2 keyboard. If you're using a USB keyboard, you can capture it through the virtual machine's USB settings. This is usually more trouble than it's worth.

**Comment by thibpoullain** [comment]
You're right, but it works out of the box ! My apple USB keyboard is recognize and available in the preferences settings. Perfect thx for your help !
