### ISSUE TITLE
macOS guest virtualbox error in WSL

### ISSUE THREAD

**Issue by FellFromTheSky** [myspaghetti/macos-guest-virtualbox#201]
I'm using macOS guest virtualbox 0.90.5 as sudo su 
and it's not working on WSL Ubuntu.
I'm using dmg2img  1.6.7 deb because I wasn't able to download it trough sudo apt-get install dmg2img.
I tried it both with and without admin rights.
I'm always getting this error :
Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseSystem.vdi"...
VBoxManage.exe: error: Cannot open file "Catalina_BaseSystem.img": VERR_FILE_NOT_FOUND
Failed to create "Catalina_BaseSystem.vdi". Exiting.

**Comment by myspaghetti** [comment]
Regarding the package - make sure you update your package list, `dmg2img` is [available on all Canonical-supported Ubuntu distros](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=dmg2img&searchon=names).

Regarding running with elevated privileges - don't. Running the script with elevated privileges creates file permissions issues for VirtualBox. It's generally a bad idea to run untrusted software with elevated privileges. Delete the files created with elevated permissions or fix the permissions of the files.

If you're still having read/write issues, check your version of Windows. The script warns that some versions of WSL (on Windows 10 versions 1809 and earlier) require running the script on the Windows filesystem, that is under the WSL path `/mnt/drive_letter/path`

**Comment by FellFromTheSky** [comment]
Ok thanks.
Anyway the 0.90.5 script works well as sudo su on Linux (KDE neon).
