### ISSUE TITLE
macOS Mojave Installation doesn't work either

### ISSUE THREAD

**Issue by Animenosekai** [myspaghetti/macos-guest-virtualbox#204]
Hey, thanks for your last reply. I tried to install macOS Mojave this time, thinking that it could fix the problem. Though, I'm stuck at another stage (yea unfortunately):
This time I have a problem with the first terminal stage, macOS guest is saying that there is an error while concatenating `InstallESD.part03` `InstallESD.part04` `InstallESD.part05` : `/Volumes/macOS Base System 1/Install macOS Mojave.app/Contents/Shared Support//InstallESD.dmg` and I tried to cd into `/Volumes/` and as I saw, there is no `macOS Base System 1` directory.

**Comment by Animenosekai** [comment]
<img width="920" alt="Capture d’écran 2020-05-09 à 14 24 03" src="https://user-images.githubusercontent.com/40539549/81473825-9d4e5300-9201-11ea-8f85-943ba8914777.png">

`troubleshoot`:
[log.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4603447/log.txt)

**Comment by myspaghetti** [comment]
The log says `Mojave_BaseSystem.vdi` is not attached.

**Comment by myspaghetti** [comment]
Looks like the drive was ejected in the middle of the concatenation process...

**Comment by myspaghetti** [comment]
Please mind that the troubleshooting log contains all the information about the virtual machine configuration, including serials and UUIDs, so it's better to either use the default values like `NO_DEVICE_SN` when troubleshooting.

**Comment by Animenosekai** [comment]
> Please mind that the troubleshooting log contains all the information about the virtual machine configuration, including serials and UUIDs, so it's better to either use the default values like `NO_DEVICE_SN` when troubleshooting.

Oh damn you right!
Thank you for removing it!
