### ISSUE TITLE
The script is not robust to errant keyboard keystrokes

### ISSUE THREAD

**Issue by ianmacs** [myspaghetti/macos-guest-virtualbox#63]
The terminal where the script runs, reads
```
Starting virtual machine macOS Mojave. This should take a couple of minutes.
Waiting for VM "macOS Mojave" to power on...
VM "macOS Mojave" has been successfully started.

Press enter when the Language window is ready.
```

Meanwhile, the VM seems to run in a reboot loop. I'm not sure if this is normal and included in the "This should take a couple of minutes". I think I have waited for about 10 reboots now. The last thing displayed before rebooting is:
![VirtualBox_macOS Mojave_03_06_2019_21_31_24](https://user-images.githubusercontent.com/3147421/58829483-30712700-8648-11e9-8eac-fd735640a885.png)

The host system is ubuntu 19.04 with CPU i5-8250U. Any ideas?

**Comment by bradjasperson** [comment]
Having the same issue with Windows 10. I noticed that the terminal throws a restore command not found error in the previous step. That's my guess as to why it's not working.

**Comment by img2tab** [comment]
This error very likely happens because [the script is not robust to errant keyboard strokes](https://github.com/img2tab/macos-guest-virtualbox/issues/51). I still don't have a proper solution for this that doesn't require more dependencies than I'd like to have.

**Comment by img2tab** [comment]
See also [issue 5](https://github.com/img2tab/macos-guest-virtualbox/issues/5), [issue 51](https://github.com/img2tab/macos-guest-virtualbox/issues/51)

**Comment by myspaghetti** [comment]
Should be less of a problem from version 0.80.0 onward. Not fixed but not as severe any more.
