### ISSUE TITLE
Expand APFS from command line

### ISSUE THREAD

**Issue by DuBistKomisch** [myspaghetti/macos-guest-virtualbox#77]
Hi, great script, just a small suggestion for the final step.

Instead of telling people to figure out  how to use Disk Utility, the same operation is possible with this command: `sudo diskutil apfs resizeContainer disk1 0`.

**Comment by myspaghetti** [comment]
Implemented in [commit 471034417a7d10795044959ddf5d66b522abf4ac](https://github.com/myspaghetti/macos-guest-virtualbox/commit/471034417a7d10795044959ddf5d66b522abf4ac#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by kgraefe** [comment]
This should also be changed within [the script][1], no?

Despite, it does not seem to work for me:

```
$ sudo diskutil apfs resizeContainer disk1 0
Password:
Started APFS operation
Error: -69743: The new size must be different than the existing size
```

I don't know the Disk Utility, but I guess it already is okay:
![VirtualBox_macOS_17_09_2019_18_24_35](https://user-images.githubusercontent.com/3797324/65060615-814b2800-d978-11e9-9531-d17b335a3e1a.png)


[1]: https://github.com/myspaghetti/macos-guest-virtualbox/blob/master/macos-guest-virtualbox.sh#L925

**Comment by myspaghetti** [comment]
Don't forget to resize the VDI file from VirtualBox first.
