### ISSUE TITLE
Never got to Licence prompt

### ISSUE THREAD

**Issue by jelabarre59** [myspaghetti/macos-guest-virtualbox#79]
The install process worked all the way up to the point where it was supposed to show the License prompt.  However, once the terminal ran the command immediately prior to where the prompt should have appeared, it simply went to the prompt and did nothing else.  

So I had the installer script contnue whatever else it was going to do, and eventually the VM came up to an EFI Shell, and never went any further.

**Comment by myspaghetti** [comment]
I believe this is a result of [errant keystrokes](https://github.com/myspaghetti/macos-guest-virtualbox/issues/63) which broke the script somewhere along the way. Please start the script over (keep the temporary files so you don't have to redownload them) and see if you get to the installer this time.

**Comment by myspaghetti** [comment]
Closing until further details are provided.

**Comment by jelabarre59** [comment]
Just FYI; I had tried the script a couple more times and didn't even get as far as I had previously.  So I haven't been able to provide useful debug info.  Eventually I'll have time to try it again.

**Comment by jelabarre59** [comment]
Rebooted system, and then only opened a terminal window (no email, browser, etc).  Also rather than switching between windows with <alt>-<tab> instead clicked on application windows to make them active.  Install went all the way through (Mojave).

Will be useful to see what changed after High Sierra (which is the highest my MBP supports).
