### ISSUE TITLE
Boot hangs on LoadKernelFromStream, EndRandomSeed, or EXITBS

### ISSUE THREAD

**Issue by widberg** [myspaghetti/macos-guest-virtualbox#8]
Windows 10 host
VirtualBox 5.2.2

The VM boots and freezes at this screen for a couple of seconds
![c91f8d21-1e90-459e-85d7-57cb39ea0e99](https://user-images.githubusercontent.com/6676723/49618490-d0dedb00-f986-11e8-9bf5-a243077991de.jpeg)
Then it continues on and freezes permanently at this screen
![e11f2509-9293-4f63-bd86-e02fadd3b71c](https://user-images.githubusercontent.com/6676723/49618491-d0dedb00-f986-11e8-92f1-d519cca0fc2c.jpeg)

I got this to work with both a Windows and Linux host on a different physical machine. I don’t understand why it isn’t working on this machine because I’m following the same steps and the hardware configuration is almost identical to that of the one it worked on. If you need anymore information just ask. Thank you in advance!

**Comment by ISTEricBrown** [comment]
Having same issue

**Comment by img2tab** [comment]
@ISTEricBrown @prowolf  Does this still occur if you disable uninstall HyperV?

**Comment by prowolf** [comment]
I have HyperV disabled.

**Comment by juancgarcia** [comment]
I'm also hanging at `EndRandomSeed`. I'm on an AMD based system (Ryzen 3 2200g if that might make any difference).

I've tried modifying script with `modifyvm "Mojave" --cpu-profile "Intel Core i7-6700K"` as suggested [on reddit](https://www.reddit.com/r/hackintosh/comments/9xvspq/stuck_at_end_randomseed_on_mojave_in_virtualbox/ecrqxtn/) but this yields a "Critical Error" which halts the VM.

Any thoughts?

**Comment by fractal1510** [comment]
> I'm also hanging at `End RandomSeed`. I'm on an AMD based system (Ryzen 3 2200g if that might make any difference).
> 
> I've tried modifying script with `modifyvm "Mojave" --cpu-profile "Intel Core i7-6700K"` as suggested [on reddit](https://www.reddit.com/r/hackintosh/comments/9xvspq/stuck_at_end_randomseed_on_mojave_in_virtualbox/ecrqxtn/) but this yields a "Critical Error" which halts the VM.
> 
> Any thoughts?

Exactly the same problem but mine managed to boot with different cpu profile, try following profiles:

VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core i7-2635QM"
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core i5-3570"
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core i7-5600U"
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Core i7-6700K"

Mine booted with VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Xeon X5482 3.20GHz"

**Comment by prowolf** [comment]
@img2tab, following @fractal1510's suggestion of using `VBoxManage modifyvm "Mojave" --cpu-profile "Intel Xeon X5482 3.20GHz"` worked for me. I have tried using other cpu profiles in the past with no luck, but at least `Intel Xeon X5482 3.20GHz` works for me now.

**Comment by juancgarcia** [comment]
@fractal1510 I got mine to boot with "Intel Core i7-2635QM"

Thanks!

**Comment by juancgarcia** [comment]
I got the VM to boot with:
```
 --cpu-profile "Intel Xeon X5482 3.20GHz" \
 --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
```
Cheers.

(found another issue, but I'll post in a new thread)

**Comment by alizardx** [comment]
i have a Quad core AMD A8-7600 
tried all the CPU settings - original error except for
i7-2635qm critical error

**Comment by redcode** [comment]
I made Mojave work in VirtualBox on Gentoo Linux using:
`VBoxManage modifyvm "Mojave" --cpu-profile "Intel Core i7-2635QM"`

Mobo: ASUS Sabertooth 990FX
CPU: FX-8150
RAM: 16GB Corsair Domminator Platinum 1600MHz

**Comment by jarcane** [comment]
On WSL in Windows 10, I'm failing at applying the `--cpu-profile` parameter because VBoxManage seems to be confused by the spaces in the profile.

I just get some variation of `VBoxManage.exe: error: Invalid parameter 'Core'`. I've tried escaping the spaces but that was no help.

I see there's actually a mention of this in the script around the `microsoft_path` variable, but is there any similar trick to something like the `--cpu-profile` string value?

**Comment by img2tab** [comment]
@jarcane use Windows's `cmd.exe` command line to launch `VBoxManage`, that way it accepts variables with spaces.

**Comment by mikekenyon99** [comment]
Just to confirm, using VB on AMD Ryzen7 2700 and mine got stuck at `End Random Seed` Mine booted with `VBoxManage modifyvm "Mojave" --cpu-profile "Intel Xeon X5482 3.20GHz`

**Comment by hyperpanthera** [comment]
This fixes the issue.

> VBoxManage modifyvm "PARSE_NAME_OF_VM_HERE" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff

**Comment by hnetorj** [comment]
> This fixes the issue.
> 
> > VBoxManage modifyvm "PARSE_NAME_OF_VM_HERE" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff

Wow It's true, I did it!

**Comment by hyperpanthera** [comment]
@hnetorj No problem. The creator of the script should add it.

**Comment by img2tab** [comment]
Same as [issue 66](https://github.com/img2tab/macos-guest-virtualbox/issues/66), this fix is hardware-specific. Putting it in the script might do more harm than good until there's a robust method to detect whether or not a specific hardware configuration requires these settings.

**Comment by hnetorj** [comment]
> Same as [issue 66](https://github.com/img2tab/macos-guest-virtualbox/issues/66), this fix is hardware-specific. Putting it in the script might do more harm than good until there's a robust method to detect whether or not a specific hardware configuration requires these settings.

Looking from your point of view, you're right.

**Comment by Phaeilo** [comment]
I'm running Virtualbox 6.0.8 on Archlinux with a AMD FX-4100. Besides using `--cpuidset` and `--cpu-profile` I also had to specify `--nestedpaging off` in order for the VM to boot successfully.

**Comment by t3dc** [comment]
Trying to get this running on an old Mac Pro 1,1 running Fedora 30. Using the various --cpu-profile options gets me past the "End Random Seed." However, I still get the kernel error and the virtual machine kernel panics in an endless reboot loop without ever reaching the install screen.

The machine has 2x4 core 3.0Ghz procs and 32gb of ram, but they are all basically Core2 era processors. Can someone give me some configuration suggestions? I have tried both the --cpuidset and --nestedpaging suggestions, though I don't know how to set appropriate cpuid values for my hardware.

**Comment by leamas** [comment]
The Ryzen random generator problems are a "known" (citation needed) issue which should be fixed by very latest BIOS updates.

**Comment by kenshaw** [comment]
I don't plan on submitting a PR, or anything, however I created a branch of the script that adds the `--cpu-profile` and `--cpuidset` flags, and changes some other variables around to work (verified) out of the box with Gen 1, 2, and 3 Ryzen Ubuntu hosts. 

See: https://github.com/kenshaw/macos-guest-virtualbox/tree/add-ryzen-profile

This is likely handy for others who also need to change those settings in this script. 

To @myspaghetti really appreciate the work on this project! I'd be glad to do a formal PR with changes, but as you had mentioned (here or elsewhere) this is hardware dependent, and an attempt should be to automate this. I'd be glad to make the changes needed, if you could provide guidance on what would be acceptable.

**Comment by myspaghetti** [comment]
@kenshaw Thank you!

The biggest issue with maintaining this workaround is keeping a list of which CPUs need which options. I'm not inclined to maintain such a list, and I doubt anybody else would like to, either.

Does the issue apply to all Ryzen CPUs? What about Ryzen CPUs with patched microcodes? If not, is there a robust way to check the microcode version? Do they all require the exact same workaround or is the workaround slightly different for different models? This is a lot of work, so the "known issues" section will have to do.

**Comment by myspaghetti** [comment]
And there are reports of the issue for Intel CPUs too, [like this one](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8#issuecomment-511385199). Really feel like implementing an automatic workaround would require too much time.

**Comment by kenshaw** [comment]
My suggestion would be to just have the variables in the script somewhere, so they can be tailored by the user. My guess is that the clock speed + core count of the chip id, as well as the profile set more or less need to be the same as the underlying hardware, and mesh with what's been set in VirtualBox. All three Ryzen processors I tried this with, have 8 or more cores (16 or more threads), and I was setting the VirtualBox vm as having 4 cores on each. The configuration I used worked on a Ryzen 7 1800x, Ryzen 5 2600x, a Ryzen 2990wx, and a Ryzen 9 3900x.

**Comment by LociCantos** [comment]
Same problem
P5W DH Deluxe
Q6600
Intel 975X +Intel ICH7R
![Q6600 Intel 975x vbox-mohave-install](https://user-images.githubusercontent.com/44733700/65073965-b8a1e080-d948-11e9-959d-6cc513225a80.png)

**Comment by deakjahn** [comment]
What should also be noted that it's worth experimenting with the number of processors in the VM. I had cases when 1 worked and anything above 1 did not.

**Comment by afillat** [comment]
I'm new to this script, but I just ran the unmodified script version 0.87.7 with VirtualBox 6.14.136177 (a couple of days old) and got the exact same failure as above (Mojave VM stops with End Random Seed). I am running the script on Cygwin on Windows 10 pro fully updated. Processor/system is a vanilla 10th gen Intel i7. I have been unable to create a VM by any other means that will run iMessage, etc. I see many suggestions but cannot sort out which might apply (e.g. running only the configure_VM option with the script on a configured VM). Any advice?

**Comment by myspaghetti** [comment]
@afillat it's very possible that the currently-available versions of macOS are not compatible with 10th gen Intel Core processors. [Try one of these CPU profiles.](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8#issuecomment-453847710) When the VM fails to boot, enter the command and start the VM manually (`VBoxManage startvm "${vm_name}"`) or add the line to the `configure_vm` stage.

**Comment by afillat** [comment]
Thanks. I used the Intel Core i7-6700K profile and was able to create the guest. The script is awesome when it works. Unfortunately, my existing Apple ID won't authenticate. So there is still something missing. When I did this in VMware a year ago using osX Sierra I could get it to work, but the version of the workstation was so unstable in the face of events like sleep I had to abandon it. The following lines were added to their VMX file:
efi.nvram.var.ROM.reflectHost = FALSE
efi.nvram.var.MLB.reflectHost = FALSE
efi.nvram.var.ROM = 123456
efi.nvram.var.MLB = DONKDONKDONKDONKA
Perhaps you can suggest analogous edits for your script. Who knows if it still works. (Is there a way to apply these to the existing VirtualBox VM instead of recreating it?)

**Comment by myspaghetti** [comment]
Make sure you set the NVRAM parameters by running the EFI Internal Shell.

**Comment by myspaghetti** [comment]
@afillat Make sure you set the NVRAM parameters in the script and apply them by running the EFI Internal Shell. Read `./macos-guest-virtualbox.sh documentation` for the process to get Apple ID working.

**Comment by afillat** [comment]
I got everything done, but cannot get to the EFT Internal Shell to run the startup script. VB gets to the boot process even if I am holding down the escape key at start. It probably doesn’t capture the keyboard fast enough. Can I run it using VBManage or Cygwin?

**Comment by myspaghetti** [comment]
@afillat I deleted your message because it had your personal GitHub unsubscribe URL in it.

Regarding the EFI Internal Shell, if you can't get to it manually, then change the storage controller from AHCI (SATA) to NVMe (PCIe). VirtualBox will still recognize the EFI System Partition but will not be able to boot from it. VirtualBox will drop into the EFI Internal Shell automatically and run `fs0:\startup.nsh`

**Comment by myspaghetti** [comment]
@afillat I deleted your message because it had your personal GitHub unsubscribe URL in it.

Regarding the EFI Internal Shell, if you can't get to it manually, then change the storage controller from AHCI (SATA) to NVMe (PCIe). VirtualBox will still recognize the EFI System Partition but will not be able to boot from it. VirtualBox will drop into the EFI Internal Shell automatically and run `fs0:\startup.nsh`

After that, you can return the storage controller to AHCI and boot macOS.

**Comment by afillat** [comment]
I REALLY appreciate your help. I have gotten everything to work EXCEPT iMessage. I can log onto my AppleID and use iCloud. That is something that didn’t work in prior tries. I even ran the script to create a new Catalina VM, but the result was the same. Something must be missing or awry, or Apple has erected higher barriers around this app.

I will understand if you are played out on this, so continue only if you want.

Just for reference, here are all the parameters I used (they are modeled after a MacBook on which I ran the indicated terminal commands; I couldn’t seem to find the Board-id):

vm_name="OSXCat"                  # name of the VirtualBox virtual machine
macOS_release_name="Catalina"      # install "HighSierra" "Mojave" or "Catalina"
storage_size=80000               # VM disk image size in MB. Minimum 22000
cpu_count=4                      # VM CPU cores, minimum 2
memory_size=8092                 # VM RAM in MB, minimum 2048
gpu_vram=128                     # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution


DmiSystemFamily="MacBook Pro"        # Model Name
DmiSystemProduct="MacBookPro11,2"    # Model Identifier
DmiSystemSerial="C08WE06A8HHBA"       # Serial Number (system) (actual)C02WD068HH26
DmiSystemUuid="DAFECAFE-CAFE-CAFE-CAFE-DECAFFDECAFF" # Hardware UUID
DmiOEMVBoxVer="string:1"             # Apple ROM Info
DmiOEMVBoxRev="string:.23456"        # Apple ROM Info
DmiBIOSVersion="string:MBP7.89"      # Boot ROM Version
# ioreg -l | grep -m 1 board-id
DmiBoardProduct="Mac-3CBD00234E554E41"
# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB (actual)C028093015AHJD41V
DmiBoardSerial="C02AB93087ABHD41X"
MLB="${DmiBoardSerial}"
# nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM (used actual)
ROM='%8f*f0*%dcx%1e'
# ioreg -l -p IODeviceTree | grep \"system-id
SYSTEM_UUID="DAFECAFE-CAFE-CAFE-CAFE-DECAFFDECAFF"
# csrutil status
SYSTEM_INTEGRITY_PROTECTION='10'  # '10' - enabled, '77' – disabled


I have not deleted the working files, so I still have Catalina_Installation_files.viso if an edit is called for.

**Comment by myspaghetti** [comment]
@afillat you posted your personal GitHub unsubscribe URL again. Since this has gone off-topic, please start a separate issue.

Help yourself better by:
* Not posting URLs that might give other people access to your account settings.
* Not posting your genuine Mac serial number and other genuine details.

**Comment by LEXUGE** [comment]
On ThinkPad X1 Carbon 7th Gen, i7-10710U, 

`VBoxManage modifyvm "Mojave" --cpu-profile "Intel Xeon X5482 3.20GHz"`
works

**Comment by daniele777** [comment]
Guys i have AMD Ryzen 3 1200 3.10 gz 8 gb ram..stuck at End Random Seed if i try another cpu solution going crash...directly...help!"

**Comment by richardcrossley** [comment]
#### Resolved
The install became stuck before the language screen appeared. Changing the CPU profile allowed the install to proceed.

```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
```

It was then necessary to restart the installation process:
```
./macos-guest-virtualbox.sh populate_virtual_disks
```

#### Hardware
CPU: Ryzen 3 3900x
Motherboard: Asus X570-PRO
GPU: NVidia GTX 1660

#### Software
Host OS: Linux Mint 19.3 64bit
VirtualBox: Version 6.1.6 r137129 (Qt5.9.5)

**Comment by ardhitama** [comment]
Win: `2004` (slow ring)
Vbox: `6.1.97` (dev)

Problem:

1. Catalina unable to boot with last error: `EXITBS:START`

Steps that solved my problem:

1. Elevated powershell: `bcdedit /set hypervisorlaunchtype off`
2. Restart Windows
3. `VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"`

**Comment by myspaghetti** [comment]
Added the workaround to the documentation.

**Comment by flikQ** [comment]
> Win: `2004` (slow ring)
> Vbox: `6.1.97` (dev)
> 
> Problem:
> 
> 1. Catalina unable to boot with last error: `EXITBS:START`
> 
> Steps that solved my problem:
> 
> 1. Elevated powershell: `bcdedit /set hypervisorlaunchtype off`
> 2. Restart Windows
> 3. `VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"`

Attempted this work around with a corei9 9900k and no dice sadly.

**Comment by anaisbetts** [comment]
On Arch Linux + Ryzen 3400G, "Intel Xeon X5482 3.20GHz" will allow the machine to boot 🎉

**Comment by MeguMario** [comment]
for some reason, mine is a loop of kernel panic, nothing works
https://streamable.com/0g3y27

**Comment by MeguMario** [comment]
for some reason, mine is a loop of kernel panic, nothing works
https://streamable.com/0g3y27

**Comment by ramlancan** [comment]
mine boot up with "Intel Core i7-2635QM" line, thank @fractal1510

**Comment by maximgeerinck** [comment]
Thanks, adding `VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"` worked.

i modified it on line `641` (` ...--mouse usbtablet --keyboard usb --audiocontroller hda --audiocodec stac9221 --cpu-profile "Intel Xeon X5482 3.20GHz"`)

**Comment by MrTob** [comment]
no one of the suggested solutions worked for me.

Specs:
Win 10
AMD ryzen 7 3700X
24 GB Ram
Geforce 1060

**Comment by mikeschuld** [comment]
> error: `EXITBS:START`
> 1. Elevated powershell: `bcdedit /set hypervisorlaunchtype off`

This was the only thing that solved it for me

**Comment by myspaghetti** [comment]
@mikeschuld what version of the script are you using that it doesn't detect that Hyper-V is enabled?

**Comment by mikeschuld** [comment]
Just downloaded the current master yesterday and got this. Here's a screenshot for reference:

![image](https://user-images.githubusercontent.com/565158/99561638-6ad99b80-2984-11eb-8665-3bb62bcd840b.png)

**Comment by myspaghetti** [comment]
If Hyper-V is enabled, the script should output the following:
```
Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.
```
Did you not get this error message?

**Comment by Aiosa** [comment]
> no one of the suggested solutions worked for me.
> 
> Specs:
> Win 10
> AMD ryzen 7 3700X
> 24 GB Ram
> Geforce 1060

See the "elevated powershell way", that worked for me (same CPU)

**Comment by andrew-aladev** [comment]
This [configuration](https://gist.github.com/movibe/b9707f1b4b2674e1c5749fdc4b1f94b6) is fine for almost any ryzen.
