### ISSUE TITLE
Lower dependency version to 5.2

### ISSUE THREAD

**Issue by bridgesense** [myspaghetti/macos-guest-virtualbox#81]
I didn't have any issues at all lowering the dependency version to 5.2 and running this script.
I'd wager that most of the Linux community is stuck in 5.2 as 6.0 has some serious hangups.

**Comment by myspaghetti** [comment]
Apparently VISO is available as early as VirtualBox 5.2.2 so I'll lower the required version to that.

**Comment by myspaghetti** [comment]
Lowered required VBox version to 5.2.2 in version 0.71.3

**Comment by Echolon** [comment]
Hi,

thank you for your script and work.

However, I had VB 6.1 installed or as now again VB _5.2.34_Ubuntur133883_

Still, the script stops with:

`Please make sure VirtualBox version 5.2 or higher is installed.
Exiting.`

which breaks in line 253. 

Do you have any clue why VM is seemingly mislinked?

System: Kubuntu 18.04.

**Comment by myspaghetti** [comment]
@Echolon what's the output of `VBoxManage -v`?
