### ISSUE TITLE
Check Hyper-V feature is not installed before running VM

### ISSUE THREAD

**Issue by Zhangwei-WU** [myspaghetti/macos-guest-virtualbox#82]
First of all, it's a great script! it works so beautiful! :) 
I suffered a lot of errors/kernel panic during installation: errors when boot, cannot go to language page, and even in Utilities page when try to open Terminal then kernel panic. 

After all of those, I realized that **Hyper-V** feature installed in my Windows 10 caused all of these suffers, after I uninstall the Hyper-V, everything goes smoothly.

So if would be great if the script checks Hyper-V before VM installation

**Comment by myspaghetti** [comment]
Sorry, I don't think I'll be implementing a Hyper-V test even if all it involves is calling PowerShell with `get-service | findstr vmcompute` because VirtualBox already warns the user that it doesn't work with Hyper-V enabled.
