### ISSUE TITLE
on ubuntu 19.04 - bad loop variable

### ISSUE THREAD

**Issue by muelli75** [myspaghetti/macos-guest-virtualbox#90]
Hi!

Using v 0.73.2 on ubuntu 19.04, its throwing

./macos-guest-virtualbox.sh: 52: ./macos-guest-virtualbox.sh: Syntax error: Bad for loop variable

any ideas how to solve this? thank you!

**Comment by myspaghetti** [comment]
Please make sure you are running the script on bash version 4.0 or higher
