### ISSUE TITLE
MacOS Catalina Read-Only...

### ISSUE THREAD

**Issue by dadons7** [myspaghetti/macos-guest-virtualbox#96]
Again, thank you for your awesome Spaghetti Code!!!
Also, I have a Linux Host with a Mac Guest and SIP is now disabled - thanks to your help!

In Catalina, is there a simple way to make the root drive be Read-Write permanently?

For now, I am using: "mount -uw /" at the terminal.

Tried crontab, which I know is depreciated and it is not working.

Any ideas would be greatly appreciated.

**Comment by myspaghetti** [comment]
macOS root is read-write by default.

**Comment by dadons7** [comment]
Thank you for your prompt response.

It is my understanding that the latest MacOS Catalina installs two volumes,
a data and a system. The Data is read-write however the System is read-only.
In other words, even though I have disabled SIP and login as a Root user
if I go to the root "/" then it is read-only. I can not even make a directory to
the root of the drive. So, as a Root user I execute "mount -uw /" and then I can
make a directory..

My question is:
Is there a way to boot into Catalina so that the system drive is read-write?

Thank you

**Comment by myspaghetti** [comment]
Oh, looks like the current beta sets the root directory as read-only by default. Sorry for answering without checking.

**Comment by dadons7** [comment]
Jack,

Thank you for checking. Yes, another security feature to protect
us from ourselves. I have been on Ubuntu for 15 years and Windows
for over 30 and I can not remember ever deleting a system file
that was needed. Same with viruses and the like, over 30 years and none.
I run a hardware firewall in which I block everything - then only open 
the minimum
incoming and out going ports - simple. In addition, I use iptables on every
Host and VM. Not to mention, with VirtualBox I just clone the machine as 
needed
and I can restore in minutes.

Developers do not need SIP and read-only drives. Therefore, it would be nice
if you could give us an option when installing to disable SIP and or 
Read-Only.

Your scripting and coding skills are amazing!

I can not image figuring out all of those commands in order to install 
the macOS.

Well done!

Mark Astengo
